import { defineMiddleware } from 'astro:middleware';
import { validateSession } from './lib/auth';

const PUBLIC_PATHS = ['/', '/login', '/api/auth/login', '/api/auth/logout'];

// Mirrors backoffice/public/_headers, which only covers static assets — with
// output: 'server' every HTML/API response is generated by this Pages
// Function and needs the same security headers applied here.
const SECURITY_HEADERS: Record<string, string> = {
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
  'Content-Security-Policy':
    "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; frame-src https://challenges.cloudflare.com; img-src 'self' data:; connect-src 'self' https://challenges.cloudflare.com",
};

function withSecurityHeaders(res: Response): Response {
  if (res.status >= 300 && res.status < 400) {
    // Redirects: leave untouched (Location must not be disturbed).
    return res;
  }
  for (const [name, value] of Object.entries(SECURITY_HEADERS)) {
    res.headers.set(name, value);
  }
  return res;
}

export const onRequest = defineMiddleware(async (context, next) => {
  const path = new URL(context.request.url).pathname.replace(/\/+/g, '/');

  // Allow public paths
  if (PUBLIC_PATHS.some(p => path === p || path.startsWith(p + '/'))) {
    // If already logged in and visiting /login, redirect to dashboard
    if (path === '/login') {
      const token = context.cookies.get('session')?.value;
      const env = (context.locals as any).runtime?.env;
      if (token && env?.DB) {
        const valid = await validateSession(env.DB, token);
        if (valid) {
          return context.redirect('/dashboard');
        }
      }
    }
    const res = await next();
    return withSecurityHeaders(res);
  }

  // Check auth for all other routes
  const token = context.cookies.get('session')?.value;
  const env = (context.locals as any).runtime?.env;

  if (!token || !env?.DB) {
    return context.redirect('/login');
  }

  const valid = await validateSession(env.DB, token);
  if (!valid) {
    context.cookies.delete('session', { path: '/' });
    return context.redirect('/login');
  }

  const res = await next();
  return withSecurityHeaders(res);
});
