-- ============================================
-- BULK CONTENT SEED
-- ============================================

-- INSULTI (category_id = 1) — usa {name} come placeholder
INSERT INTO text_responses (category_id, content) VALUES
(1, '{name}, sei così inutile che se fossi un''app saresti Internet Explorer.'),
(1, 'Ma {name}, quando parli fai venire nostalgia del silenzio.'),
(1, '{name} è la prova vivente che anche i preservativi hanno una percentuale di fallimento.'),
(1, 'Se la stupidità fosse un superpotere, {name} sarebbe un Avenger.'),
(1, '{name}, hai la personalità di un semaforo spento.'),
(1, 'Ma {name}, da piccolo giocavi col mercurio?'),
(1, '{name}, sei talmente brutto che quando sei nato il dottore ha schiaffeggiato tua madre.'),
(1, 'Ogni volta che {name} parla, un neurone muore di solitudine.'),
(1, '{name}, se il cervello fosse dinamite, non ti basterebbe per farti saltare il cappello.'),
(1, 'Ho visto pozzanghere con più profondità di {name}.'),
(1, '{name}, sei il motivo per cui gli shampoo hanno le istruzioni.'),
(1, 'Se {name} fosse un condimento, sarebbe la farina.'),
(1, '{name}, hai la faccia come un distributore di schiaffi.'),
(1, 'Ma {name}, ti hanno allattato con la grappa?'),
(1, '{name}, non sei stupido. Sei solo sfortunato a pensare.'),
(1, 'Hai presente il fondo del barile? Ecco, {name} sta scavando.'),
(1, '{name}, se l''ignoranza fosse ricchezza saresti Jeff Bezos.'),
(1, '{name} è così lento che quando corre lo doppia un parchimetro.'),
(1, 'Se {name} avesse un euro per ogni idea intelligente, sarebbe in debito.'),
(1, '{name}, sei la versione umana di un lunedì mattina.'),
(1, 'Ma {name}, tuo padre era un clown o è un talento naturale?'),
(1, '{name}, hai il carisma di una sedia vuota.'),
(1, 'Se la noia avesse un volto, sarebbe quello di {name}.'),
(1, '{name}, sei così falso che il Made in China ti fa i complimenti.'),
(1, 'Ma {name}, quando Dio distribuiva il cervello tu eri in bagno?'),
(1, '{name}, hai meno utilità di un paracadute bucato.'),
(1, 'Se {name} fosse una spezia, sarebbe il sale scaduto.'),
(1, '{name}, sei l''errore 404 dell''evoluzione umana.'),
(1, 'Quando {name} parla, anche Siri dice "non ho capito".'),
(1, '{name}, porti sfiga anche ai gatti neri.'),
(1, 'Se {name} fosse un film, sarebbe diretto da Uwe Boll.'),
(1, '{name}, hai la simpatia di un''unghia incarnita.'),
(1, 'Ma {name}, ti sei laureato su YouTube?'),
(1, '{name} è il tipo di persona che Google non riesce a trovare.'),
(1, 'Se {name} fosse una canzone, sarebbe quella dell''attesa telefonica.'),
(1, '{name}, sei così noioso che i sonniferi ti prendono prima di dormire.'),
(1, '{name}, hai la grazia di un ippopotamo sul ghiaccio.'),
(1, 'Se {name} fosse un Pokemon, sarebbe Magikarp. Senza evoluzione.'),
(1, '{name}, ogni tua parola è un attentato alla mia pazienza.'),
(1, 'Ma {name}, quando ti guardi allo specchio, lo specchio si gira?');

-- MINACCE (category_id = 2) — usa {name} come placeholder
INSERT INTO text_responses (category_id, content) VALUES
(2, '{name}, ti faccio diventare un ricordo.'),
(2, 'Ancora una parola {name} e ti mando in orbita a calci.'),
(2, '{name}, ti strappo le braccia e ti applaudo con quelle.'),
(2, 'Guarda che a {name} lo seppellisco sotto il parcheggio dell''Esselunga.'),
(2, '{name}, ti faccio fare la fine del pandoro a Natale.'),
(2, '{name}, un''altra così e ti trasformo in un caso irrisolto.'),
(2, 'Ti prendo a schiaffi così forte {name} che ti stacco il codice fiscale.'),
(2, '{name}, ti faccio un lifting a calci in faccia.'),
(2, 'Stai attento {name}, che ti faccio vedere le stelle senza telescopio.'),
(2, '{name}, ti piego in quattro e ti metto nella busta delle lettere.'),
(2, '{name}, ti faccio diventare un mobile IKEA: in pezzi e senza istruzioni.'),
(2, 'Ti lancio così lontano {name} che atterri nel Medioevo.'),
(2, '{name}, giuro che ti faccio sparire come i calzini nella lavatrice.'),
(2, 'Ti mando talmente in alto {name} che ti serve il passaporto per tornare.'),
(2, '{name}, ti faccio un nodo alle gambe e ti uso come fermaporta.'),
(2, 'Ancora un po'' {name} e ti faccio rimpiangere di essere nato.'),
(2, '{name}, ti faccio correre talmente tanto che bruci più calorie di un maratoneta.'),
(2, 'Ti do un calcio così forte {name} che arrivi prima dell''ambulanza.'),
(2, '{name}, ti smonto come un mobile dell''IKEA e ti rimonto male.'),
(2, 'Ti prendo {name} e ti uso come scopa per pulire il pavimento.'),
(2, '{name}, ti faccio fare un giro nel cestello della lavatrice.'),
(2, 'Guarda che ti pianto {name} come un albero e ti innaffio con il cemento.'),
(2, '{name}, ti faccio mangiare la tastiera lettera per lettera.'),
(2, 'Ti lancio dalla finestra {name}, e abito al piano terra così soffri di più.'),
(2, '{name}, ti trasformo in un soprammobile.'),
(2, 'Ti do una testata {name} che ti sposto la data di nascita.'),
(2, '{name}, ti mando al creatore con la raccomandata.'),
(2, 'Ti faccio nero {name}, ma non come l''abbronzatura.'),
(2, '{name}, ti apro come una scatoletta di tonno.'),
(2, 'Stai zitto {name} o ti faccio parlare in corsivo... dalla botta.');

-- BESTEMMIE (category_id = 3) — esclamazioni creative
INSERT INTO text_responses (category_id, content) VALUES
(3, 'Porco il mondo e chi ci sta dentro!'),
(3, 'Mannaggia a tutti i santi del calendario!'),
(3, 'Per tutti i demoni dell''inferno e anche quelli in ferie!'),
(3, 'Maledizione su questa giornata e su chi l''ha inventata!'),
(3, 'Che il cielo ti caschi in testa a fette!'),
(3, 'Mannaggia la miseria e chi la porta!'),
(3, 'Per tutte le bestie del creato!'),
(3, 'Accidenti a te e a chi ti ha messo al mondo!'),
(3, 'Mannaggia al giorno che sono nato!'),
(3, 'Per tutti i fulmini di Giove!'),
(3, 'Maledetta la terra che calpesti!'),
(3, 'Porco il destino e chi lo governa!'),
(3, 'Mannaggia alla mia pazienza che non esiste più!'),
(3, 'Per tutte le disgrazie dell''universo!'),
(3, 'Accidenti al cielo e a chi ci abita!'),
(3, 'Mannaggia a sto mondo di ladri!'),
(3, 'Per tutti i diavoli dell''inferno e del purgatorio!'),
(3, 'Maledetto il giorno, l''ora e il minuto!'),
(3, 'Porco tutto e il contrario di tutto!'),
(3, 'Mannaggia alla vacca e al vitello!'),
(3, 'Per tutte le piaghe d''Egitto!'),
(3, 'Accidenti a questa vita grama!'),
(3, 'Mannaggia a chi non si fa i fatti propri!'),
(3, 'Per tutte le maledizioni dell''antico testamento!'),
(3, 'Porco il fato e la sorte cieca!'),
(3, 'Mannaggia al cielo, alla terra e al mare!'),
(3, 'Che ti venga un colpo secco!'),
(3, 'Per tutti i serpenti dell''Eden!'),
(3, 'Mannaggia la miseria ladra!'),
(3, 'Accidenti a sta vita e a chi la vive male!');

-- COME DICEVA MIO NONNO (category_id = 4) — perle di saggezza
INSERT INTO text_responses (category_id, content) VALUES
(4, 'Come diceva mio nonno: "Chi va a letto senza cena, tutta la notte si dimena."'),
(4, 'Come diceva mio nonno: "Meglio un asino vivo che un dottore morto."'),
(4, 'Come diceva mio nonno: "Chi non beve in compagnia o è un ladro o è una spia."'),
(4, 'Come diceva mio nonno: "A lavare la testa all''asino si perde il ranno e il sapone."'),
(4, 'Come diceva mio nonno: "Donna al volante, pericolo costante."'),
(4, 'Come diceva mio nonno: "Chi troppo vuole nulla stringe, chi poco chiede in culo prende."'),
(4, 'Come diceva mio nonno: "Il mattino ha l''oro in bocca, il pomeriggio il cazzo in saccoccia."'),
(4, 'Come diceva mio nonno: "Chi dorme non piglia pesci, ma almeno non rompe i coglioni."'),
(4, 'Come diceva mio nonno: "Patti chiari, amicizia lunga. Patti scuri, ti spezzo le gambe."'),
(4, 'Come diceva mio nonno: "Fidarsi è bene, non fidarsi è meglio, stare a casa è il massimo."'),
(4, 'Come diceva mio nonno: "L''ospite è come il pesce, dopo tre giorni puzza."'),
(4, 'Come diceva mio nonno: "Chi fa da sé fa per tre, chi fa per gli altri è un coglione."'),
(4, 'Come diceva mio nonno: "Moglie e buoi dei paesi tuoi, amanti da dove cazzo ti pare."'),
(4, 'Come diceva mio nonno: "Chi nasce tondo non muore quadrato, chi nasce stronzo muore incazzato."'),
(4, 'Come diceva mio nonno: "Non fare oggi quello che puoi rimandare a domani, tanto domani non lo fai comunque."'),
(4, 'Come diceva mio nonno: "Ride bene chi ride ultimo, ma intanto io rido adesso."'),
(4, 'Come diceva mio nonno: "La vita è come una bicicletta: se non pedali caschi. E se pedali sudi."'),
(4, 'Come diceva mio nonno: "Chi si accontenta gode, chi non si accontenta va su Tinder."'),
(4, 'Come diceva mio nonno: "Occhio per occhio, dente per dente, corna per corna, parente per parente."'),
(4, 'Come diceva mio nonno: "Il vino fa buon sangue, la grappa fa buon tutto."'),
(4, 'Come diceva mio nonno: "Una mela al giorno toglie il medico di torno, una grappa al giorno toglie tutto di torno."'),
(4, 'Come diceva mio nonno: "Tra il dire e il fare c''è di mezzo il mare, e io non so nuotare."'),
(4, 'Come diceva mio nonno: "Chi la fa l''aspetti, chi l''aspetta s''addormenta."'),
(4, 'Come diceva mio nonno: "Non c''è due senza tre, non c''è tre senza un quarto di vino."'),
(4, 'Come diceva mio nonno: "A caval donato non si guarda in bocca, ma nel culo sì."'),
(4, 'Come diceva mio nonno: "L''erba del vicino è sempre più verde perché la concima con le stronzate."'),
(4, 'Come diceva mio nonno: "Chi va piano va sano e va lontano, chi va forte va all''ospedale."'),
(4, 'Come diceva mio nonno: "Natale con i tuoi, Pasqua con chi vuoi, Ferragosto col condizionatore."'),
(4, 'Come diceva mio nonno: "Il denaro non fa la felicità, ma è meglio piangere in Ferrari."'),
(4, 'Come diceva mio nonno: "Dio li fa e poi li accoppia, il diavolo li mette nello stesso ufficio."');

-- SALUTI (category_id = 5) — saluti coloriti
INSERT INTO text_responses (category_id, content) VALUES
(5, 'Buongiorno brutti stronzi! Che la giornata vi sia meno peggio del solito!'),
(5, 'Buonasera a tutti i degenerati di questo gruppo!'),
(5, 'Buonanotte manica di sfigati! Sognate qualcosa di bello per una volta!'),
(5, 'Ehi razza di disgraziati, buongiorno!'),
(5, 'Buondì, facce di bronzo! Pronti per un''altra giornata di merda?'),
(5, 'Salutiamo questa massa di ignoranti con affetto! Buongiorno!'),
(5, 'Buongiorno a chi se lo merita! Quindi non a voi.'),
(5, 'Buonasera gente! Spero che la vostra giornata sia stata una merda come la mia!'),
(5, 'Ciao belli! E quando dico belli intendo brutti.'),
(5, 'Buongiorno! Oggi è un altro giorno per deludermi, e voi siete bravissimi!'),
(5, 'Sveglia coglioni! Il sole è alto e voi siete bassi!'),
(5, 'Buonanotte! Che possiate sognare di essere persone migliori!'),
(5, 'Buongiorno a tutti! Tranne a chi sa di doversi vergognare.'),
(5, 'Ehilà banda di scappati di casa! Come butta?'),
(5, 'Buonasera signori e signore... sto parlando con voi, branco di animali!'),
(5, 'Oh ma buongiorno! Credevo foste tutti morti, invece siete solo inutili!'),
(5, 'Ciao a tutti quelli che non hanno niente di meglio da fare! Cioè tutti voi.'),
(5, 'Buondì, branco di parassiti! Oggi chi rompe i coglioni per primo?'),
(5, 'Buongiorno principesse! Principesse del cazzo, ma pur sempre principesse.'),
(5, 'Buonanotte fetenti! Domani è un altro giorno per fregarvi a vicenda!'),
(5, 'Salve, gentaglia! SborrBot vi augura il meglio del peggio!'),
(5, 'Buongiorno a questa fogna a cielo aperto che chiamate chat!'),
(5, 'Ehilà teste di cazzo! Tutto bene? Tanto non me ne frega.'),
(5, 'Buonasera a tutti i falliti riuniti! Che bel gruppo che siete!'),
(5, 'Buongiorno! Ricordate: oggi peggio di ieri, meglio di domani!'),
(5, 'Ciao rifiuti della società! SborrBot è qui per voi!'),
(5, 'Buondì cari! "Cari" nel senso che costate troppo per quello che valete.'),
(5, 'Buonanotte a tutti! Che il vostro sonno sia disturbato come la vostra mente!'),
(5, 'Buongiorno allo zoo! Oggi le scimmie sono particolarmente attive!'),
(5, 'Salve a tutti, belli e brutti! Ma soprattutto brutti.');
