-- Anti-Juve: categoria e insulti per chi nomina la Juventus

INSERT INTO categories (slug, name, type, description) VALUES
  ('anti-juve', 'Anti-Juve', 'text', 'Insulti automatici per chi nomina la Juventus');

INSERT INTO text_responses (category_id, content) VALUES
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, hai nominato la Juve? Ma vaffanculo te e quei ladri di merda dei tuoi beniamini.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Oh {name} pezzo di merda, parli della Juve? L''unica squadra con più processi penali che trofei legittimi, cazzo.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, tifare Juventus è come essere orgogliosi di avere la gonorrea. Sei un coglione e lo sai.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Senti {name}, la Juventus ha rubato più scudetti che porcoddio hai detto tu in vita tua. E tu ne dici tanti, stronzo.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, ogni volta che nomini la Juve un arbitro si sente una mano nel culo. Quella di Moggi, quel figlio di puttana.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Ma {name}, cazzo nomini la Juventus? Quella squadra di merda che senza rubare non vinceva manco a briscola col nonno?'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juve è come la diarrea: ti viene quando meno te l''aspetti, puzza di merda e ti rovina la cazzo di giornata.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Ehi {name} stronzo, lo sai qual è la differenza tra la Juve e un cesso? Il cesso almeno è onesto quando è pieno di merda.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, se la Juve fosse un piatto sarebbe una merda fumante guarnita con le lacrime degli arbitri che si sono venduti. Mangiala, coglione.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name} parla della Juventus... madonna puttana, che coraggio del cazzo. Come vantarsi di aver vinto rubando, porco dio.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Oh {name}, la Juve in Champions League fa più figure di merda di te quando apri quella cazzo di bocca, e ce ne vuole, testa di cazzo.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, tifare Juve nel 2025 è come andare in giro con la faccia di Moggi tatuata sul culo. Che cazzo di vergogna, dio bestia.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, Calciopoli non è stata un''ingiustizia, porcodio. L''ingiustizia è che un coglione come te possa ancora parlare di quella merda di squadra.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Ma {name}, con quella bocca di merda nomini la Juventus? Lavati i denti, il culo e la coscienza, pezzo di stronzo.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juve è l''unica squadra di merda al mondo che riesce a far addormentare 80.000 coglioni contemporaneamente. Compreso te.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Hai detto Juve, {name}? Porcoddio, mi è appena venuto un conato di vomito. Ringraziami che non ti mando anche quello addosso.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, i tifosi della Juve sono come gli stronzi nel cesso: puzzano, galleggiano e non se ne vanno mai affanculo.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, lo sai che la Juve è gemellata col carcere di Rebibbia? Stessi inquilini, stessa mentalità di merda, cazzo.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Ehi {name}, la prossima volta che nomini quella merda di Juve ricordati che Calciopoli non è un quartiere di Torino, coglione.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juventus è come il tuo futuro: una merda totale, senza gloria e basata sulle raccomandazioni. Vaffanculo.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, preferisco ficcarmi un trapano nel culo piuttosto che guardare la Juve giocare. E preferisco essere sordo piuttosto che sentirti parlarne, stronzo.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Oh {name}, lo sapevi? Il VAR è stato inventato perché la Juve rubava come dei figli di puttana. E infatti hanno smesso di vincere, porcodio.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, nomini i bianconeri come se fosse qualcosa di cui andare fieri, coglione. L''unico bianco e nero che vi si addice è quello delle foto segnaletiche, maledetti ladri del cazzo.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juve ha più scheletri nell''armadio che cazzi in culo hai preso tu. E ne hai presi tanti, fidati.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Senti {name} testa di minchia, ogni volta che qualcuno dice "Juventus" un pallone si sgonfia dalla vergogna e un arbitro si tocca il culo per i flashback.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, tifare Juve è come farsi una sega con la carta vetrata: fa male, è stupido e solo un coglione come te può goderne.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juventus senza furti arbitrali è come te senza stronzate da dire: non esiste, cazzo. Fattene una ragione.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Ehi {name}, l''ultimo scudetto pulito della Juve risale a quando tua madre era ancora vergine. Cioè mai, porcodio.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, sei juventino? Minchia, questo spiega perché sei un coglione totale senza gusto, dignità e un cazzo di senso critico.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juve è come la sifilide: nessuno la vuole, si diffonde tra i coglioni e alla fine ti fa marcire, dio cane.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Oh {name}, la Juve in Europa fa la figura del cazzo come un preservativo bucato: inutile e piena di buchi.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, se gli scudetti rubati fossero cazzi, la Juve sarebbe il più grande porno della storia. E tu saresti lì a guardare, segaiolo di merda.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, il gioco della Juventus è talmente di merda che la UEFA lo usa come punizione per i carcerati. Manco loro lo meritano, porcodio.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Ma {name}, parli della Juve con quella faccia di culo? Siete fatti l''uno per l''altra: brutti da cagare e impossibili da sopportare.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la bacheca della Juve è come il tuo culo: piena di roba che non dovrebbe starci. Dio porco.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, ho più rispetto per la merda che calpesto che per chi tifa Juventus. Almeno la merda non ruba gli scudetti, coglione.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Ehi {name}, lo sai perché la Juve gioca in bianco e nero? Perché i colori se li sono fatti sequestrare insieme alla dignità, quei ladri del cazzo.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juve è come una malattia venerea: te la becchi quando frequenti gente di merda, tipo te, coglione.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, se la Juve fosse un film sarebbe un porno di quelli brutti: tutti fingono, nessuno gode e alla fine ti senti una merda. Come te.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Oh {name}, parli di Juventus? L''unica cosa che quei gobbi di merda hanno vinto con merito è il titolo di squadra più odiata del cazzo d''Italia.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juve è la dimostrazione che puoi comprare tutto tranne la dignità. Un po'' come te che non te la puoi permettere, porcodio.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, ma lo sai che "gobbo" significa anche "disonesto"? Che cazzo di coincidenza, come te che sei gobbo dentro e fuori, stronzo.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, ogni volta che nomini la Juve, da qualche parte Moggi si masturba. E tu sei il suo materiale, porco dio che schifo.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Senti {name}, la Juventus è come le emorroidi: un dolore al culo cronico e parlarne fa schifo a tutti. Come te, coglione.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, il tuo amore per la Juve mi conferma che hai gusti di merda in tutto. Nella squadra, nella vita, in tutto cazzo.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, se dovessi scegliere tra guardare Juve-Empoli e ficcarmi un cactus nel culo, passami il cactus. Almeno quello ha una personalità.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Ehi {name} coglione, lo Stadium è l''unico stadio al mondo dove i tifosi festeggiano i fuorigioco a favore. Che razza di merde, porcodio.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juve ha più retrocessioni per scandali che Champions League. Pensaci, testa di cazzo, se ci riesci.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, nominare la Juventus in questa chat è come cagare sul tavolo durante la cena: tutti sanno che sei stato tu e tutti ti mandano affanculo.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Oh {name}, la Juve è l''unica squadra di merda che quando perde dice "ce l''hanno rubata" e quando vince pure gli altri dicono "ce l''hanno rubata". Ladri del cazzo.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, i gobbi sono come i pidocchi: stanno ovunque, rompono il cazzo a tutti e nessuno li sopporta. Specialmente te, stronzo.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juve senza Calciopoli è come te senza cazzate: un concetto puramente teorico, porcodio.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, hai presente quando la Juve è andata in Serie B? Cazzo, quello è stato il giorno più bello della storia del calcio. Peccato che sono risaliti, sti figli di puttana.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Ma {name}, come cazzo fai a nominare la Juve senza vomitarti addosso? A me viene il cagotto solo a sentirla, dio bestia.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, tifare Juventus è come mangiare la merda e dire che è cioccolato: puoi provarci, ma fai schifo a tutti. Coglione.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la prossima volta che dici "Juve" in questa chat ti mando Nedved a romperti le gambe. Quello almeno era bravo a fare i falli di merda.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Ehi {name}, se i processi fossero trofei, la Juventus sarebbe la squadra più titolata della galassia. Maledetti ladri figli di puttana.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juve è come il lunedì mattina dopo una sbronza: nessuno la vuole, ti fa sentire di merda e ti chiedi che cazzo ci fai qui. Come te in questa chat.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, parli dei bianconeri? L''unico nero che vedranno quest''anno è quello del lutto per la stagione di merda. E l''unico bianco è la bandiera della resa, porcodio.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, se la mediocrità fosse un campionato, la Juve lo vincerebbe. Ah no, aspetta, pure quello lo ruberebbero, quei figli di troia.');
