-- Anti-Juve: categoria e insulti per chi nomina la Juventus

INSERT INTO categories (slug, name, type, description) VALUES
  ('anti-juve', 'Anti-Juve', 'text', 'Insulti automatici per chi nomina la Juventus');

INSERT INTO text_responses (category_id, content) VALUES
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, hai nominato la Juve? Complimenti, hai appena dimostrato di avere il QI di un guardalinee corrotto.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Oh {name}, parli della Juve? L''unica squadra che ha più processi che trofei legittimi.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, tifare Juventus è come essere orgogliosi di copiare all''esame e farsi beccare comunque.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Senti {name}, la Juventus ha rubato più scudetti che gol fatti con merito. E tu li difendi? Vergognati.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, ogni volta che nomini la Juve un arbitro da qualche parte sente un brivido di nostalgia.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Ma {name}, lo sai che "Juventus" in latino significa "gioventù"? Peccato che la vostra storia faccia invecchiare di schifo.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juve è come un peto in ascensore: la senti, puzza, e tutti sanno chi è stato ma nessuno ha il coraggio di dire niente.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Ehi {name}, lo sai qual è la differenza tra la Juve e una banconota falsa? Nessuna, entrambe cercano di passare per buone.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, se la Juve fosse un piatto sarebbe una minestra riscaldata condita con le lacrime degli arbitri onesti.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name} parla della Juventus... che coraggio. Come vantarsi di aver vinto a Monopoli barando.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Oh {name}, la Juve in Champions League fa più figure di merda di te quando apri bocca, e ce ne vuole.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, tifare Juve nel 2025 è come andare in giro con la maglia di Schettino. Imbarazzante.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, Calciopoli non è stata un''ingiustizia. L''ingiustizia è che gente come te esista e tifi pure Juve.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Ma {name}, con quella bocca nomini la Juventus? Lavati i denti e la coscienza.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juve è l''unica squadra al mondo che riesce a far addormentare 80.000 persone contemporaneamente. Che talento.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Hai detto Juve, {name}? Mi è appena venuto un conato. Grazie.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, i tifosi della Juve sono come le zanzare: fastidiosi, inutili e nessuno li ha mai invitati.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, lo sai che la Juve è gemellata con il Monopoli? No aspetta, al Monopoli almeno si gioca pulito.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Ehi {name}, la prossima volta che nomini la Juve ricordati che Calciopoli non è un quartiere di Torino.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juventus è come il tuo futuro: triste, senza gloria vera e basata sulle raccomandazioni.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, preferisco infilarmi le dita negli occhi piuttosto che guardare la Juve giocare. E preferisco tapparmi le orecchie piuttosto che sentirti parlarne.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Oh {name}, lo sapevi? Il VAR è stato inventato per far smettere la Juve di rubare. E infatti hanno smesso di vincere.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, nomini i bianconeri come se fosse qualcosa di cui andare fieri. L''unico bianco e nero che vi si addice è quello delle foto segnaletiche.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juve ha più scheletri nell''armadio che coppe meritate. Un po'' come te che hai più scuse che risultati.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Senti {name}, ogni volta che qualcuno dice "Juventus" un pallone da qualche parte si sgonfia dalla vergogna.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, tifare Juve è come mettere il ketchup sulla carbonara: tecnicamente puoi farlo, ma sei una persona orribile.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juventus senza furti arbitrali è come te senza cazzate da dire: non esiste.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Ehi {name}, l''ultimo scudetto pulito della Juve risale a quando tuo nonno aveva ancora i capelli. E tuo nonno è calvo da 40 anni.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, sei juventino? Questo spiega molte cose. Tipo la tua totale mancanza di gusto, dignità e senso critico.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juve è come un virus: nessuno la vuole, si diffonde lo stesso e alla fine ti fa stare male.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Oh {name}, la Juve in Europa fa la figura del panettone a Ferragosto: nessuno la vuole e tutti la evitano.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, se gli scudetti rubati valessero punti, la Juve vincerebbe davvero qualcosa. Ah no aspetta, neanche così.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, il gioco della Juventus è talmente bello che la UEFA lo usa come cura per l''insonnia.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Ma {name}, parli della Juve con quella faccia? Siete fatti l''uno per l''altra: brutti da vedere e difficili da sopportare.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la bacheca della Juve è come il tuo curriculum: piena di roba gonfiata e poco verificabile.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, ho più rispetto per chi mette l''ananas sulla pizza che per chi tifa Juventus. Almeno quello è un crimine senza vittime.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Ehi {name}, lo sai perché la Juve gioca in bianco e nero? Perché i colori se li sono fatti togliere per cattiva condotta.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juve è come un''influenza: ti prende quando sei debole, ti fa delirare e alla fine ti vergogni di averla avuta.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, se la Juve fosse un film sarebbe una fiction di Mediaset: tutti sanno che è finta ma qualche pirla ci crede ancora.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Oh {name}, parli di Juventus? L''unica cosa che i gobbi hanno vinto con merito è il titolo di squadra più odiata d''Italia.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juve è la dimostrazione che con i soldi e le conoscenze giuste puoi vincere anche senza dignità. Un po'' come te nella vita.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, ma lo sai che "gobbo" in italiano significa anche "disonesto"? Che coincidenza, eh?'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, ogni volta che nomini la Juve, da qualche parte Moggi sorride. E quando Moggi sorride, il calcio piange.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Senti {name}, la Juventus è come le emorroidi: un dolore al culo che non se ne va mai e di cui ti vergogni a parlare.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, il tuo amore per la Juve mi conferma che hai pessimo gusto in tutto. TUTTO.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, se dovessi scegliere tra guardare Juve-Empoli e farmi trapanare un ginocchio, passami il trapano.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Ehi {name}, lo Stadium è l''unico stadio al mondo dove i tifosi festeggiano i fuorigioco a favore come se fossero gol.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juve ha più retrocessioni per scandali che Champions League. Pensaci.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, nominare la Juventus in questa chat è come scoreggiare in ascensore: tutti sanno che sei stato tu e tutti ti odiano.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Oh {name}, la Juve è l''unica squadra che quando perde dice "ce l''hanno rubata" e quando vince... anche gli altri dicono "ce l''hanno rubata".'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, i gobbi sono come i piccioni: stanno ovunque, cagano su tutto e nessuno li sopporta.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juve senza Calciopoli è come tu senza stronzate: un concetto puramente teorico.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, hai presente quando la Juve è andata in Serie B? Ecco, quello è stato il momento più bello della storia del calcio italiano.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Ma {name}, come fai a nominare la Juve senza che ti si chiuda lo stomaco? A me succede solo a sentirla.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, tifare Juventus è un po'' come votare il peggio alle elezioni: lo fai perché non hai alternative o perché sei proprio de coccio.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la prossima volta che dici "Juve" in questa chat ti mando Nedved a farti un tackle. Quello vero, non quello che simulava.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), 'Ehi {name}, se i processi fossero trofei, la Juventus sarebbe la squadra più titolata della galassia.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, la Juve è come il lunedì mattina: nessuno la vuole, arriva lo stesso e ti rovina la giornata.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, parli dei bianconeri? Guarda che l''unico nero che vedranno quest''anno è quello del lutto per la stagione.'),
  ((SELECT id FROM categories WHERE slug = 'anti-juve'), '{name}, se la mediocrità fosse un campionato, la Juve lo vincerebbe. Ah no, aspetta, pure quello lo ruberebbero.');
