-- ============================================
-- EXTRA DIRTY CONTENT - Il peggio del peggio
-- ============================================

-- INSULTI CATTIVISSIMI (category_id = 1)
INSERT INTO text_responses (category_id, content) VALUES
(1, '{name}, sei così brutto che tua madre ti allattava bendato.'),
(1, '{name}, hai la faccia che sembra un incidente stradale al rallentatore.'),
(1, '{name}, se la merda potesse cagare, cagirebbe te.'),
(1, '{name}, sei il pelo incarnito sul culo dell''umanità.'),
(1, '{name}, tua madre avrebbe dovuto ingoiare.'),
(1, '{name}, sei talmente cesso che quando entri in bagno il water vomita.'),
(1, '{name}, hai meno valore di un rutto in ascensore.'),
(1, '{name}, se ti mettessero il prezzo saresti nell''angolo delle offerte.'),
(1, '{name}, puzzi di più di un cassonetto ad agosto.'),
(1, '{name}, il tuo albero genealogico è un cerchio.'),
(1, '{name}, sei la diarrea dell''evoluzione.'),
(1, '{name}, hai la personalità di una supposta usata.'),
(1, '{name}, tuo padre doveva venire sul muro.'),
(1, '{name}, sei così stupido che annegheresti in una pozzanghera.'),
(1, '{name}, la tua faccia fa più danni di un terremoto.'),
(1, '{name}, se il cesso avesse un volto, avrebbe il tuo.'),
(1, '{name}, hai la simpatia di un''emorroide infiammata.'),
(1, '{name}, sei il tipo di persona che si perde in un corridoio.'),
(1, '{name}, hai più peli che neuroni.'),
(1, '{name}, anche il tuo cane si vergogna di te.'),
(1, '{name}, sei nato il primo aprile? Perché sei uno scherzo della natura.'),
(1, '{name}, quando il dottore ti ha visto nascere ha chiesto il rimborso.'),
(1, '{name}, sei la versione sfigata di uno sfigato.'),
(1, '{name}, se fossi un supposta almeno serviresti a qualcosa.'),
(1, '{name}, hai meno fascino di un pannolino sporco.'),
(1, '{name}, tua madre ti ha partorito per scommessa e ha perso.'),
(1, '{name}, sei il motivo per cui certi animali mangiano i propri figli.'),
(1, '{name}, se il tuo QI fosse temperatura saresti sotto zero.'),
(1, '{name}, la tua esistenza è un errore di battitura nel codice genetico.'),
(1, '{name}, fai più pena di un clown al funerale.'),
(1, '{name}, hai l''aspetto di chi è stato concepito su un cassonetto.'),
(1, '{name}, sei così insignificante che il GPS ti perde.'),
(1, '{name}, hai il fascino di una scoreggia silenziosa in ascensore.'),
(1, '{name}, sei il sottoprodotto di una serata andata male.'),
(1, '{name}, quando Dio ti ha creato stava guardando dall''altra parte.'),
(1, '{name}, sei come un peto: nessuno ti vuole ma arrivi comunque.'),
(1, '{name}, hai meno dignità di un bidet rotto.'),
(1, '{name}, la tua faccia sembra il prima in una pubblicità di chirurgia plastica.'),
(1, '{name}, se la sfiga avesse un ambasciatore, saresti tu.'),
(1, '{name}, sei la prova che Dio ha il senso dell''umorismo.'),
(1, '{name}, fai schifo anche alla muffa.'),
(1, '{name}, sei il tipo che si siede sul cazzo e si lamenta del mal di schiena.'),
(1, '{name}, hai la grazia di un maiale su un trampolino.'),
(1, '{name}, se fossi un sapore saresti il vomito.'),
(1, '{name}, la tua esistenza è un''offesa a chi ha lottato per evolversi.'),
(1, '{name}, sei così inutile che nemmeno come cattivo esempio funzioni.'),
(1, '{name}, hai più problemi di un aeroporto con la nebbia.'),
(1, '{name}, sei il fallimento che i tuoi genitori non ammetteranno mai.'),
(1, '{name}, anche il nulla è più interessante di te.'),
(1, '{name}, se fossi cibo saresti la muffa sul cibo.');

-- MINACCE DIABOLICHE (category_id = 2)
INSERT INTO text_responses (category_id, content) VALUES
(2, '{name}, ti infilo la testa nel forno e ci faccio la pizza.'),
(2, '{name}, ti strappo la spina dorsale e ci suono il basso.'),
(2, '{name}, ti faccio un culo così grande che ci parcheggi un TIR.'),
(2, '{name}, ti spezzo le dita una per una e le uso come stuzzicadenti.'),
(2, '{name}, ti sciolgo nell''acido e ti vendo come detersivo.'),
(2, '{name}, ti stacco la testa e ci gioco a bowling.'),
(2, '{name}, ti faccio ingoiare i denti come fossero Tic Tac.'),
(2, '{name}, ti apro come un tonno e ti condisco con il limone.'),
(2, '{name}, ti metto nel frullatore e ti servo al bar.'),
(2, '{name}, ti faccio volare così in alto che ti trovano i satelliti.'),
(2, '{name}, ti faccio un culo talmente grande che ci entra l''autostrada.'),
(2, '{name}, ti strappo le orecchie e ci faccio i ravioli.'),
(2, '{name}, ti faccio correre così tanto che ti ritrovi in un altro fuso orario.'),
(2, '{name}, ti rompo in così tanti pezzi che nemmeno la Lego ti rimonta.'),
(2, '{name}, ti appendo al soffitto e ti uso come lampadario.'),
(2, '{name}, ti faccio girare così forte che diventi una lavatrice.'),
(2, '{name}, ti cago in bocca e ti chiudo il mento.'),
(2, '{name}, ti mando in ospedale con la catapulta.'),
(2, '{name}, ti prendo a calci nel culo così forte che ti escono le scarpe dalla bocca.'),
(2, '{name}, ti stiro la faccia e ci faccio una tovaglia.'),
(2, '{name}, ti faccio a pezzi e ti spedisco ai quattro angoli del mondo.'),
(2, '{name}, ti sbatto la faccia sul muro così forte che lasci l''impronta.'),
(2, '{name}, ti gonfio di botte così tanto che ti scambiano per un canotto.'),
(2, '{name}, ti pianto i denti nel muro come quadri.'),
(2, '{name}, ti arrotolo come un kebab e ti metto nella pita.'),
(2, '{name}, ti faccio il culo a strisce come una zebra.'),
(2, '{name}, ti prendo a pugni così forte che tuo nonno sente male.'),
(2, '{name}, ti appiattisco come una piadina e ti farcisco di schiaffi.'),
(2, '{name}, ti stacco le braccia e le uso come bacchette per mangiare il sushi.'),
(2, '{name}, ti faccio volare dalla finestra e ti mando le tue cose per posta.');

-- BESTEMMIE INFERNALI (category_id = 3)
INSERT INTO text_responses (category_id, content) VALUES
(3, 'Porco di quel mondo ladro infame!'),
(3, 'Mannaggia a tutti i santi, i beati e pure gli angeli in ferie!'),
(3, 'Porca di quella puttana della miseria!'),
(3, 'Mannaggia al cielo e a chi ci sta a cazzeggiare!'),
(3, 'Per tutti i demoni dell''inferno con gli straordinari!'),
(3, 'Porco di quel giuda traditore bastardo!'),
(3, 'Mannaggia alla madonna della misericordia che non ha avuto misericordia!'),
(3, 'Porca troia di quella vacca maledetta!'),
(3, 'Per tutte le bestie dell''arca di Noè e anche quelle che non sono salite!'),
(3, 'Mannaggia a sto cazzo di mondo di merda!'),
(3, 'Porco il demonio e tutti i suoi tirocinanti!'),
(3, 'Maledetto chi ha inventato questa giornata di merda!'),
(3, 'Per tutti i cazzi del purgatorio!'),
(3, 'Mannaggia alla miseria, alla fame e a chi le ha inventate!'),
(3, 'Porca di quella troia della sfortuna!'),
(3, 'Per tutti gli stronzi del paradiso!'),
(3, 'Mannaggia al cazzo e a chi lo porta!'),
(3, 'Porco il mondo, l''universo e tutte le galassie!'),
(3, 'Mannaggia alla puttana della mia sorte!'),
(3, 'Per tutte le disgrazie di sto cazzo di pianeta!'),
(3, 'Porca di quella miseria bastarda e infame!'),
(3, 'Mannaggia a tutti quanti dal primo all''ultimo!'),
(3, 'Per tutti i coglioni del firmamento!'),
(3, 'Porco il destino cieco, sordo e pure stronzo!'),
(3, 'Mannaggia a sto mondo di merda e chi lo gira!'),
(3, 'Per tutte le minchie dell''aldilà!'),
(3, 'Porca di quella troia della vita!'),
(3, 'Mannaggia a tutto il bestiario sacro e profano!'),
(3, 'Porco schifoso di quel mondo immondo!'),
(3, 'Per tutti i culi dell''inferno e anche quelli del paradiso!');

-- COME DICEVA MIO NONNO - Versione sporca (category_id = 4)
INSERT INTO text_responses (category_id, content) VALUES
(4, 'Come diceva mio nonno: "Donna barbuta, sempre piaciuta. Donna pelosa, sempre vogliosa."'),
(4, 'Come diceva mio nonno: "Chi non scopa mai, si fa le pippe e va bene lo stesso."'),
(4, 'Come diceva mio nonno: "Chi si fa i cazzi suoi campa cent''anni, chi si fa i cazzi degli altri prende le botte."'),
(4, 'Come diceva mio nonno: "La figa è come il maiale: non si butta via niente."'),
(4, 'Come diceva mio nonno: "Meglio una sega oggi che una scopata mai."'),
(4, 'Come diceva mio nonno: "A cazzo duro non c''è ragione che tenga."'),
(4, 'Come diceva mio nonno: "Chi va con lo zoppo impara a zoppicare, chi va con la troia impara a scopare."'),
(4, 'Come diceva mio nonno: "Tira più un pelo di fica che un carro di buoi."'),
(4, 'Come diceva mio nonno: "Le corna sono come i denti: quando spuntano fanno male, poi ci mangi."'),
(4, 'Come diceva mio nonno: "Chi va a letto con il culo che prude, si sveglia con il dito che puzza."'),
(4, 'Come diceva mio nonno: "Il cazzo non ha occhi, la fica non ha orecchie."'),
(4, 'Come diceva mio nonno: "Meglio cornuto che morto, almeno te la godi."'),
(4, 'Come diceva mio nonno: "Non è bello ciò che è bello, è bello ciò che fa le pompette."'),
(4, 'Come diceva mio nonno: "La vita è come un cazzo: quando si drizza si accorcia."'),
(4, 'Come diceva mio nonno: "Chi di culo ferisce, di culo perisce."'),
(4, 'Come diceva mio nonno: "Donna nuda mezza vestita, donna vestita mezza spogliata."'),
(4, 'Come diceva mio nonno: "Quando il cazzo sta in piedi il cervello sta seduto."'),
(4, 'Come diceva mio nonno: "Chi non ha mai preso un calcio nel culo non sa quanto è bello andare a piedi."'),
(4, 'Come diceva mio nonno: "Pancia piena, cazzo contento."'),
(4, 'Come diceva mio nonno: "Se la merda avesse valore, i poveri nascerebbero senza culo."'),
(4, 'Come diceva mio nonno: "Chi non beve e non scopa, in culo gli cresce l''erba."'),
(4, 'Come diceva mio nonno: "L''amore è come un peto: se lo devi forzare, probabilmente è merda."'),
(4, 'Come diceva mio nonno: "Meglio un giorno da porco che cent''anni da agnello."'),
(4, 'Come diceva mio nonno: "Chi fa il furbo col culo degli altri è sempre generoso."'),
(4, 'Come diceva mio nonno: "Non mettere il cazzo dove non metteresti il dito."'),
(4, 'Come diceva mio nonno: "La donna è come la minestra: se la lasci si fredda."'),
(4, 'Come diceva mio nonno: "Chi ha il culo caldo non apprezza la sedia."'),
(4, 'Come diceva mio nonno: "La lingua batte dove il cazzo duole."'),
(4, 'Come diceva mio nonno: "Il mondo è bello perché è avariato."'),
(4, 'Come diceva mio nonno: "A chi ti rompe il cazzo, rompigli le palle."');

-- SALUTI INFAMI (category_id = 5)
INSERT INTO text_responses (category_id, content) VALUES
(5, 'Buongiorno teste di cazzo! Oggi chi è il primo a dire una stronzata?'),
(5, 'Buonasera manica di segaioli! Come va la vita da sfigati?'),
(5, 'Buonanotte pezzi di merda! Sognate di non essere voi stessi!'),
(5, 'Buongiorno porci! Alzate quel culo dal letto e fate qualcosa di utile per una volta!'),
(5, 'Buondì figli di puttana! Pronti per un''altra giornata di merda?'),
(5, 'Buongiorno razza di coglioni! Il mondo vi odia e avete ragione!'),
(5, 'Buonasera stronzi! Spero che la giornata vi abbia trattato come meritate: di merda!'),
(5, 'Buonanotte troie! Che i vostri incubi siano belli quanto la vostra faccia!'),
(5, 'Buongiorno scarti della società! Almeno oggi provate a non essere completamente inutili!'),
(5, 'Ciao cessi ambulanti! SborrBot vi saluta con tutto il disgusto che meritare!'),
(5, 'Buongiorno vermi! Strisciate fuori dal letto e andate a farvi fottere!'),
(5, 'Buonasera merde galleggianti! Come state? Tanto non me ne fotte un cazzo!'),
(5, 'Buondì rifiuti umani! Oggi cercate almeno di non peggiorare la situazione!'),
(5, 'Buongiorno a tutti i coglioni qui presenti! E non manca nessuno!'),
(5, 'Buonanotte bastardi! Che il materasso vi inghiotta!'),
(5, 'Ehi facce di culo! Buongiorno dal vostro bot preferito!'),
(5, 'Buongiorno brutti stronzi! Il vostro livello di schifo oggi è particolarmente alto!'),
(5, 'Buonasera maiali! Uscite dal fango e rispondete a SborrBot!'),
(5, 'Buondì cerebrolesi! Oggi chi mi fa perdere la pazienza per primo?'),
(5, 'Buongiorno deficienti! Avete già rotto il cazzo e sono le otto di mattina!'),
(5, 'Buonanotte cessi! Che possiate sognare di avere una vita decente!'),
(5, 'Buongiorno ritardati! L''evoluzione vi ha saltato, vero?'),
(5, 'Ciao branco di idioti! SborrBot vi ama... come si ama un''emorroide.'),
(5, 'Buonasera falliti! Anche oggi non avete combinato un cazzo, vero?'),
(5, 'Buondì stronzetti! Oggi il vostro livello di merda supererà se stesso!'),
(5, 'Buongiorno a sto branco di scimmie! Almeno le scimmie lanciano la merda con precisione!'),
(5, 'Buonanotte fetentoni! Che il cuscino sia caldo da entrambi i lati!'),
(5, 'Buongiorno! Siete la dimostrazione che non tutti meritano l''ossigeno gratis!'),
(5, 'Buonasera sottospecie! Anche i batteri vi guardano dall''alto in basso!'),
(5, 'Buondì merde ambulanti! SborrBot vi augura tutto il peggio!');
