-- SborrBot: Diagnosi, Notizie, Chi È, Lamenti + Emoji Reactions
-- 4 nuove categorie, 315 contenuti

-- ============================================================
-- NUOVE CATEGORIE
-- ============================================================

INSERT INTO categories (slug, name, type, description) VALUES
  ('diagnosi', 'Diagnosi Medica', 'text', 'Referti medici assurdi e volgari'),
  ('notizie', 'Notizia Flash', 'text', 'Titoli di giornale trash su utenti del gruppo'),
  ('chi-e', 'Chi È', 'text', 'Bio inventate e volgari su una persona'),
  ('lamenti', 'Reazione ai Lamenti', 'text', 'Risposte sarcastic ai piagnistei');

-- ============================================================
-- 80 DIAGNOSI MEDICHE
-- ============================================================

INSERT INTO text_responses (category_id, content) VALUES
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Il paziente {name} è affetto da sindrome da testa nel culo cronica, fase terminale. La prognosi è pessima come lui/lei.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Referto medico: {name} presenta evidenti sintomi di ignoranza acuta combinata con stupidità cronica. Non è curabile.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Dopo attenta visita, {name} risulta affetto/a da vuoto pneumatico cranico con frequenti esacerbazioni durante le riunioni.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Diagnosi: {name} soffre di imbecillismo galoppante con complicazioni di arroganza. Consigliato l''isolamento immediato.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} presenta atrofia cerebrale diffusa con aumento della massa adiposa tra le orecchie. Caso raro ma non abbastanza.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Referto: {name} soffre di laringite da cazzate continue. Consigliato silenzio forzato per almeno 30 anni.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Diagnosi di {name}: cretinismo acquisito con episodi ricorrenti di figura di merda acuta. Frequenza: quotidiana.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Il paziente {name} è positivo al test della stupidità. Risultato: abbondantemente fuori scala.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} è affetto/a da sindrome del copertone bucato: parla tanto ma non va da nessuna parte.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Referto urgente per {name}: cervello di dimensioni ridotte, probabilmente rudimentale. Servono ulteriori analisi ma la speranza è poca.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} presenta i classici sintomi del pagliaccio cronico: non prende niente sul serio, tranne se stesso/a.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Risultato esami: {name} ha il QI in negativo. In trent''anni di medicina non avevo mai visto tanto.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} è affetto/a da faccia di culo congenita, non operabile. La famiglia è stata informata.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Diagnosi per {name}: memoria selettiva per le proprie cazzate, eccellente memoria per quelle altrui.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} soffre di sindrome dell''orologio rotto: ha ragione solo due volte al giorno.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Il paziente {name} presenta lesioni al lobo del buon senso, probabilmente atrofizzato dalla nascita.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Referto: {name} è allergico/a al lavoro. Esposizione minima provoca reazione immunitaria intensa.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} è clinicamente incompatibile con il concetto di utilità sociale. Consigliato cambiamento radicale di tutto.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Il caso di {name} è unico: riesce a dire cazzate anche in silenzio. Fenomeno da studiare.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} presenta sindrome da specchio rotto: crede di essere bellissimo/a mentre la realtà è ben documentata.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Diagnosi: {name} soffre di cleptomania emotiva — ruba energia a chi gli/le sta vicino senza mai dare nulla in cambio.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Referto per {name}: capacità di fare figuracce superiore alla norma del 400%. Record europeo non ufficiale.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} è positivo/a alla sindrome del grande incompreso: tutti lo/la capiscono benissimo, è proprio quello il problema.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Il paziente {name} è affetto/a da procrastinazione terminale con complicazioni da divano cronico. Prognosi: rimane sul divano.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} presenta gravi lesioni al filtro delle cazzate, ormai completamente e irreversibilmente compromesso.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Dopo esame approfondito: {name} ha un talento naturale per peggiorare qualsiasi situazione esistente.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} soffre di sindrome dell''elefante nella stanza: è il problema principale ovunque vada e non se ne accorge.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Il referto è chiaro: {name} è incompatibile con la realtà. Consigliata una vita fittizia in isolamento.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Diagnosi per {name}: simpatia assente dalla nascita. Tentativo di trapianto fallito tre volte.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} presenta cellulite emotiva: tante fossette nel carattere, nessuna sostanza visibile.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Il paziente {name} è affetto/a da ipertrofia dell''ego con microatrofia del talento. Proporzione inversa.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} è clinicamente certificato/a come rompicoglioni di terzo grado con tendenza al quarto.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Risultato TAC per {name}: cranio vuoto con lieve eco quando si parla. Non è un difetto, è un''opera d''arte.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} soffre di sindrome da Dunning-Kruger avanzata: il caso da manuale che i professori usano per spiegare il fenomeno.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Referto: {name} presenta anticorpi contro il buonsenso. Il sistema immunitario rifiuta ogni logica con efficienza sorprendente.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Il dottore certifica {name} come persona ad alto rischio per la salute mentale di chi gli/le sta vicino.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} è affetto/a da verbosità acuta con complicazione silenziosa: parla molto, dice niente.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Diagnosi: {name} ha il carattere dello yogurt scaduto — acido, inutile e da buttare.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} presenta infezione cronica da complesso di superiorità non giustificato da nessuna competenza visibile.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Il paziente {name} è affetto/a da sindrome del pollo senza testa: molta agitazione, zero direzione.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} è diagnosticato/a con apatia selettiva: attivissimo/a per le cazzate, immobile per le cose serie.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Referto: {name} ha sviluppato una resistenza totale ai consigli. Casi simili nella letteratura medica: zero.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} presenta lesioni permanenti al senso del ridicolo. Non si vergogna di niente. Mai. In nessun contesto.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'La cartella clinica di {name} è la più lunga dell''ospedale. E non per le malattie fisiche, purtroppo.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} è affetto/a da sindrome del contraddittore: qualunque cosa si dica, lui/lei dice il contrario per principio.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Diagnosi finale: {name} non è curabile con la medicina tradizionale. Tentare con un calcio in culo come ultima risorsa.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} presenta elevati livelli di auto-commiserazione nel sangue. Valori fuori scala anche per gli standard SborrBot.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Il caso clinico di {name} verrà usato nelle università come esempio di cosa NON essere. Con foto inclusa.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Referto urgente: {name} è positivo/a al test dell''irresponsabilità totale. Valori massimi registrati.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} presenta sindrome da tastiera: coraggiosissimo/a per iscritto, invisibile nella vita reale.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} è affetto/a da miopia morale: vede benissimo i difetti altrui, è completamente cieco/a ai propri.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Diagnosi: {name} soffre di ernia del buonsenso. Intervento chirurgico tentato, non risolutivo.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Il paziente {name} presenta incontrollabili episodi di stronzaggine acuta, specialmente il lunedì mattina.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} è clinicamente classificato/a come persona che peggiora ogni stanza in cui entra e ogni conversazione in cui interviene.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Referto: {name} ha anticorpi contro l''umiltà. Il sistema immunitario la distrugge non appena si forma.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} presenta sindrome dell''asino dotto: sa tutto di tutto, ma capisce niente di niente.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Il caso di {name} è raro: ha trovato un modo per combinare incompetenza e arroganza in proporzioni perfette.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} è affetto/a da sindrome del salmone: nuota controcorrente non per forza ma per pura rottura di coglioni.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Diagnosi per {name}: felicità cronica nel rovinare le giornate altrui. Condizione non trattabile con farmaci noti.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} presenta livelli tossici di autocompiacimento nel sangue. Richiesta dialisi urgente del carattere.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Referto: {name} soffre di dipendenza da approvazione con crisi di astinenza ogni 10 minuti esatti.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} è positivo/a alla sindrome del capro espiatorio: la colpa è sempre di qualcun altro. Sempre. Senza eccezioni.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} presenta narcolessia della coscienza: la capacità di riflessione si addormenta esattamente quando serve.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Diagnosi: {name} è affetto/a da crollo sistemico del filtro bocca-cervello. Totale e irreversibile.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} soffre di sindrome del profeta di sventura: prevede catastrofi che non avvengono, tranne quelle che causa lui/lei.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Referto: {name} ha un talento clinico per essere nel posto sbagliato al momento sbagliato con le parole sbagliate.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} è affetto/a da anemia di personalità: tecnicamente esiste ma non si distingue da niente di niente.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} presenta osteoporosi della spina dorsale: caratterialmente privo/a di vertebre. Radiografia confermata.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Diagnosi: {name} soffre di sindrome da visibilità forzata — è ovunque ma non porta niente di utile in nessun posto.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} è affetto/a da cataratta morale: non vede la differenza tra bene e male. E sinceramente non gli/le interessa.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Referto per {name}: tossicità interpersonale elevata. Tenere a distanza di sicurezza di almeno 500 metri.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Il paziente {name} è clinicamente certificato/a come caso perso dalla medicina moderna e dall''umanità.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} è affetto/a da sindrome del cactus: spinoso/a da ogni lato, impossibile da abbracciare, inutile nella vita quotidiana.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Il dottore certifica che {name} ha raggiunto la piena consapevolezza della propria inutilità. Purtroppo se ne vanta.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} presenta eloquenza da bar: convincente in apparenza, completamente vuoto/a nel contenuto. Terapia: stare zitto/a.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Diagnosi definitiva per {name}: sindrome cronica dell''ultima parola combinata con prima parola sempre sbagliata.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), '{name} soffre di iperattività della lingua in proporzione inversa alla funzionalità del cervello. Rapporto 10:1.'),
  ((SELECT id FROM categories WHERE slug = 'diagnosi'), 'Referto finale: {name} rappresenta un pericolo per se stesso/a e per chiunque si trovi nel raggio di due metri.');

-- ============================================================
-- 100 NOTIZIE FLASH
-- ============================================================

INSERT INTO text_responses (category_id, content) VALUES
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: {name} arrestato/a a Milano mentre cercava di restituire il carrello del supermercato rubato 3 anni fa.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: {name} nominato/a nuovo/a Presidente del Consiglio dei Rompicoglioni d''Italia. Primo provvedimento: niente.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'AGGIORNAMENTO: {name} beccato/a a fare selfie davanti al bancomat mentre prende i 20 euro rimasti sul conto.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'NOTIZIA: Gli scienziati hanno scoperto che il QI medio si abbassa del 15% ogni volta che {name} apre bocca.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: {name} premiato/a come peggior presenza indesiderata del 2025 dalla Federazione Nazionale Gruppi Telegram.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: {name} segnalato/a dalle Nazioni Unite come causa principale del riscaldamento globale. L''ONU indaga.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'ESCLUSIVA: {name} ha tentato di richiedere il rimborso delle proprie tasse per "servizi non ricevuti dalla vita". Respinto.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'NOTIZIA: {name} preso/a a testate dalla realtà durante un tentativo di capire come funziona il mondo.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: La NASA conferma che {name} è la persona meno utile del sistema solare. Jupiter non è d''accordo.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: {name} denunciato/a dalla propria ombra per stalking continuo e comportamento inappropriato.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'AGGIORNAMENTO: {name} trovato/a a guardare Netflix con espressione di falsa intelligenza per le 11 ore consecutive.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'ESCLUSIVA: {name} tentativo fallito di spiegare la differenza tra latte intero e scremato. Tre ore di dibattito. Nessun vincitore.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'NOTIZIA: Il dizionario italiano ha inserito {name} come sinonimo ufficiale di "spreco di spazio atmosferico".'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: {name} bloccato/a da tutti i contatti. Record mondiale con 847 blocchi in 24 ore. La famiglia festeggia.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: {name} presenta domanda per il Grande Fratello. Rifiutata con motivazione: "troppo poco interesse anche per il trash".'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'AGGIORNAMENTO: {name} sostituito/a dalla propria pianta di ficus in qualità di miglior presenza domestica.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'ESCLUSIVA: {name} convocato/a d''urgenza dal Ministero dell''Incompetenza per premiazione con medaglia d''oro.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'NOTIZIA: Il motore di ricerca Google ha rimosso {name} dai risultati per "irrilevanza totale e documentata".'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: {name} sorpreso/a mentre copiava la lista della spesa del vicino. "Non sapevo cosa comprare da 47 anni."'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: {name} primo/a classificato/a nel concorso nazionale di figure di merda 2025. Terza vittoria consecutiva.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'AGGIORNAMENTO: {name} segnalato/a all''Agenzia delle Entrate per non aver dichiarato le proprie cazzate come reddito.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'ESCLUSIVA: {name} licenziato/a anche dal lavoro di volontariato. Motivazione: "Peggiorava tutto con la sua sola presenza."'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'NOTIZIA: La scienza ha dimostrato che stare vicino a {name} causa invecchiamento precoce di circa 3 anni al mese.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: {name} nominato/a ambasciatore/trice internazionale del disagio. Sede diplomatica: il divano di casa.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: {name} ha perso le chiavi di casa. Erano in mano. Da 3 ore. L''intervento dei pompieri ha risolto.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'AGGIORNAMENTO: Il comune di Milano ha vietato a {name} di avvicinarsi al Duomo dopo l''incidente non meglio specificato.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'ESCLUSIVA: {name} tenta di fare causa al karma per le proprie scelte di vita. Il karma ride e vince al primo grado.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'NOTIZIA: Ricercatori confermano che {name} è il motivo principale per cui l''evoluzione è troppo lenta.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: {name} ha tentato di usare la carta fedeltà della pizzeria per pagare le tasse comunali.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: {name} escluso/a dal proprio gruppo WhatsApp di famiglia per incompetenza relazionale cronica.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'AGGIORNAMENTO: {name} trovato/a a scrivere lettere di lamentele al meteo. Nessuna risposta. Mandata raccomandata.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'ESCLUSIVA: L''Istat certifica {name} come dato statisticamente irrilevante. Escluso/a dai prossimi censimenti.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'NOTIZIA: {name} ha comprato un libro di auto-miglioramento. Usato come poggiapiedi per 18 mesi consecutivi.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: {name} segnalato/a alla polizia del buon gusto per crimini reiterati contro l''estetica e il decoro.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: {name} candidato/a alle elezioni con il programma "Prometto di fare meno danni". Sconfitto/a anche dal candidato del partito del niente.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'AGGIORNAMENTO: {name} ha tentato di noleggiare un senso dell''umorismo. Deposito non rimborsato. Nessun miglioramento.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'ESCLUSIVA: La Repubblica Italiana ha dichiarato {name} patrimonio nazionale dell''incompetenza. Targa commemorativa inaugurata.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'NOTIZIA: {name} ha inviato curriculum alla NASA. Rigettato con nota manoscritta: "Neanche per lo spazio va bene."'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: {name} trovato/a a litigare con Siri. Ha perso in modo inequivocabile e umiliante.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: {name} ha tentato di fare l''influencer. I follower erano bot. I bot l''hanno bloccato/a.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'AGGIORNAMENTO: {name} nominato/a direttore/trice artistico/a della propria mediocrità con contratto a tempo indeterminato.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'ESCLUSIVA: Il telefono di {name} ha presentato richiesta di emancipazione. Accettata dal giudice tutelare.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'NOTIZIA: {name} citato/a nel Guinness World Records come persona più veloce nel rovinare una serata altrimenti salvabile.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: {name} ha perso una discussione con una cassetta della posta. La cassetta non ha detto una parola.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: Il consiglio dei ministri discute legge emergenziale per limitare le cazzate dette da {name} al giorno.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'AGGIORNAMENTO: {name} ha ricevuto il premio "Presenza meno necessaria dell''anno" dalla propria famiglia riunita in sessione plenaria.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'ESCLUSIVA: {name} tenta di far causa alla propria nascita per danni morali e fisici. Il giudice si è dimesso.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'NOTIZIA: La OMS ha classificato {name} come fattore di rischio per la salute mentale di almeno 3 generazioni.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: {name} ha comprato un corso online di "Come avere successo". Il profitto netto: meno di prima.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: {name} multato/a per eccesso di mediocrità in zona residenziale. Recidivo/a.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'AGGIORNAMENTO: {name} ha tentato di brevettare la propria stupidità. Già registrata da qualcun altro nel 1987.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'ESCLUSIVA: La propria coscienza di {name} ha presentato le dimissioni per incompatibilità caratteriale.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'NOTIZIA: Scienziati confermano che la presenza di {name} abbassa la temperatura intellettuale di qualsiasi conversazione.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: {name} ha portato il gatto dal veterinario. Il veterinario ha consigliato di visitare anche {name} urgentemente.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: {name} ha tentato di fare una dieta ma ha rinunciato dopo aver letto "evitare i cibi buoni".'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'AGGIORNAMENTO: {name} ha risposto erroneamente a una domanda dello psicologo. Lo psicologo si è dimesso seduta stante.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'ESCLUSIVA: {name} ha cercato "come essere simpatico" su Google. 87 milioni di risultati. Nessuno letto.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'NOTIZIA: {name} escluso/a dalla propria squadra di calcetto. "Stavamo perdendo peggio con lui/lei in campo."'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: {name} ha telefonato al servizio clienti per reclami sul proprio carattere. In attesa da tre anni.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: La macchina di {name} si è rifiutata di accendersi. Solidarietà tra oggetti inanimati.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'AGGIORNAMENTO: {name} ha scritto un libro. Nessuno l''ha letto. Compreso {name} che l''ha dimenticato.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'ESCLUSIVA: {name} ha tentato di fare yoga. Ha fatto male a tre persone e un gatto in posizione del guerriero.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'NOTIZIA: Il proprio orologio di {name} va avanti di 15 minuti. Per evitare di doverlo aspettare.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: {name} ha perso al tris contro se stesso/a. Tre volte di fila. La stessa partita.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: {name} ha ricevuto una multa per aver occupato spazio intellettuale altrui senza permesso.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'AGGIORNAMENTO: {name} ha tentato di scrivere un testamento. Non aveva niente da lasciare. Nemmeno la dignità.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'ESCLUSIVA: {name} ha provato a fare il ghosting ma ha dimenticato di sparire. Ancora presente dopo 8 mesi.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'NOTIZIA: {name} ha tentato di spiegare una barzelletta. La barzelletta si è offesa e ha presentato denuncia.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: Gli amici di {name} hanno organizzato un piano di evacuazione per quando inizia a parlare di politica.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: {name} ha provato a imparare il tedesco. La lingua ha presentato denuncia per maltrattamenti.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'AGGIORNAMENTO: {name} ha litigato con l''autocorrettore. Il telefono ha vinto 5 a 0. {name} ha cambiato telefono.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'ESCLUSIVA: {name} ha tentato di diventare minimalista. Ha fallito tenendosi tutto, comprese le scuse accumulate.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'NOTIZIA: L''algoritmo di Instagram ha smesso di mostrare i contenuti di {name}. "Per il bene comune," spiega Meta.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: {name} ha tentato di aprire una startup. Si è startup-to male dal primo giorno. Investitori in fuga.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: Il proprio futuro di {name} ha iniziato a guardare indietro nel tempo per evitarlo attivamente.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'AGGIORNAMENTO: {name} ha chiamato il 118 per un''emergenza emotiva. Il medico ha chiesto il trasferimento.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'ESCLUSIVA: {name} ha perso una gara di cucina contro il microonde. Il microonde non aveva ingredienti.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'NOTIZIA: L''Interpol indaga su {name} per traffico internazionale di luoghi comuni e frasi fatte.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: {name} è stato/a inserito/a nella lista nera del sushi all-you-can-eat per eccessivo abuso del formato.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: {name} ha trovato 5 euro per terra. Li ha persi prima di raggiungere il portafoglio. Tragedia nazionale.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'AGGIORNAMENTO: {name} ha terminato Netflix. Ha iniziato a guardare i titoli di coda come forma di intrattenimento.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'ESCLUSIVA: {name} ha tentato di seguire una ricetta con 3 ingredienti. Ne mancavano 2 e il terzo era sbagliato.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'NOTIZIA: {name} ha chiesto indicazioni per raggiungere se stesso/a. Si è perso/a due volte. Ritrovato/a dai cani.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: L''oroscopo di {name} recita: "Evita le decisioni importanti. Evita anche quelle non importanti. Stai fermo/a."'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: {name} ha presentato domanda per diventare influencer del disagio. Accettata. Prima campagna: se stesso/a.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'AGGIORNAMENTO: {name} ha tentato di fare meditazione. I pensieri si sono rifiutati di fermarsi per 20 minuti.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'ESCLUSIVA: Il senso dell''umorismo di {name} è stato dichiarato disperso. Ricompensa per chi lo ritrova: niente.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'NOTIZIA: {name} ha partecipato a un quiz televisivo. Eliminato/a alla prima domanda: "Come si chiama?"'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: I vicini di {name} hanno presentato ricorso al comune per rumore da stupidità ad alta intensità.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: {name} ha tentato di fare il consulente finanziario. Il primo consiglio era sbagliato. Come il secondo.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'AGGIORNAMENTO: La propria agenda di {name} è piena di impegni. Tutti rimandati. Per il quarto anno consecutivo.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'ESCLUSIVA: {name} ha inventato un nuovo genere musicale. Definito dagli esperti come "insopportabile".'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'NOTIZIA: {name} ha tentato di fare il giocoliere. Ha mandato in ospedale due spettatori e un piccione.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: Il comune ha posto limiti di velocità anche per i pensieri di {name}. "Per la sicurezza di tutti."'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: {name} ha ricevuto una lettera dalla propria intelligenza. Era un addio definitivo.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'AGGIORNAMENTO: {name} ha tentato di costruire un''app. Il prototipo ha infettato 3 computer e un tostapane.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'ESCLUSIVA: Il proprio karma di {name} ha chiesto protezione internazionale per non tornare.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'NOTIZIA: {name} è stato/a bannato/a da un corso di cucina per comportamento antisociale verso la pasta.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'FLASH: {name} ha tentato di fare amicizia con la propria coscienza. Non si sono piaciuti.'),
  ((SELECT id FROM categories WHERE slug = 'notizie'), 'BREAKING: Secondo fonti attendibili, {name} è la persona più ricercata d''Italia. Per motivi non lusinghieri.');

-- ============================================================
-- 80 CHI È
-- ============================================================

INSERT INTO text_responses (category_id, content) VALUES
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}, professionista del non fare niente, esperto/a nel sembrare occupato/a a qualsiasi ora del giorno.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Chi è {name}? La risposta courte: qualcuno che occupa spazio senza giustificazione apparente o documentata.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}, nato/a sotto una cattiva stella che però era ubriaca e non stava guardando correttamente.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: conosciuto/a nel quartiere per il talento di essere nel posto sbagliato al momento sbagliato con le parole sbagliate.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Ecco {name}, l''unico/a essere vivente capace di complicare persino l''atto di respirare correttamente.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}, una leggenda vivente nel senso che nessuno capisce come faccia a sopravvivere senza assistenza.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Chi è {name}? Domanda difficile. Anche per {name} stesso/a che si perde allo specchio.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: la risposta alla domanda "cosa succede se si mescola incompetenza totale con sicurezza di sé assoluta?"'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Vi presentiamo {name}, il/la campione/ssa mondiale di delusioni reiterate e aspettative non corrisposte.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}, noto/a soprattutto per la capacità di iniziare frasi senza mai finirle e progetti senza mai iniziarli.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Ecco a voi {name}: presenza nota, contributo ignorato, ego talmente sconfinato da avere il proprio codice postale.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name} è quella persona speciale che riesce a essere protagonista di storie in cui non è mai stato/a invitato/a.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Chi è {name}? Un personaggio secondario che si crede protagonista e non ha capito il copione.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: diploma in stronzaggine, master in autocommiserazione, dottorato in fare danni involontari.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Presentiamo {name}, il/la collega che tutti fingono di non vedere in mensa da almeno tre anni.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name} è quella rara combinazione di confusione mentale totale e certezza assoluta di avere sempre ragione.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Ecco {name}, campione/ssa olimpico/a di pensieri inutili espressi sempre nel momento peggiore.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: persona di grande spessore. Purtroppo tutto orizzontale.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Chi è {name}? Il/la tipo/a che risponde alle email di spam pensando di fare una buona azione per la società.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: dotato/a di una personalità come un foglio A4. Bianco. Non rigato. Non scritto.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Vi presentiamo {name}, inventore/trice del niente, brevettatore/trice del vuoto cosmico.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name} è la prova scientifica che l''evoluzione funziona lentamente e a volte si prende una pausa molto lunga.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Ecco {name}, l''unica persona capace di litigare con una macchinetta del caffè e avere inequivocabilmente torto.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: conosciuto/a nel settore per cominciare tutto e finire niente. Due hobby, zero risultati, tanta stanchezza.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Chi è {name}? Il/la tipo/a che dice "non ho voglia" anche per le cose che ama fare da sempre.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}, amato/a da pochi, sopportato/a da molti, evitato/a da tutti quelli abbastanza svegli da farlo.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Vi presentiamo {name}: la causa principale del mal di testa di almeno tre generazioni familiari consecutive.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: laurea triennale in procrastinazione, specializzazione in scuse creative, dottorato in mancate promesse.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Ecco {name}, il/la tipo/a che porta una bottiglia d''acqua in piscina per paura della sete durante la vasca.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: stratega di professione, risultati di nessuno. Il business plan è un foglio con sopra scritto "poi vediamo".'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Chi è {name}? Quello/a che in ogni foto di gruppo è mosso/a. Anche nelle foto ferme. Anche nelle foto singole.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: noto/a per rispondere ai messaggi con la stessa tempestività con cui la lumaca corre la maratona di Milano.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Vi presentiamo {name}, detentore/trice del record mondiale di occasioni sprecate in ordine cronologico.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: capace di togliere la voglia di vivere anche alle piante grasse più resistenti.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Ecco {name}, il/la tipo/a che sbaglia il PIN del bancomat anche con i numeri scritti sulla mano.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: presente in corpo, assente in spirito, latitante in intelligenza. Tre su tre.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Chi è {name}? Il/la tipo/a che commenta le notizie senza leggerle. E ha sempre torto. Senza eccezioni.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: tecnicamente umano/a, funzionalmente un punto interrogativo con le gambe.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Vi presentiamo {name}, il/la campione/ssa di "Ho capito tutto" seguito da prova lampante del contrario immediato.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: quella persona che si presenta alle feste senza essere invitata e poi si lamenta degli antipasti.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Ecco {name}, il/la portatore/trice sano/a di caos organizzato in qualsiasi contesto sociale.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: persona di poche parole. Peccato che quelle poche siano sempre fuori luogo e fuori tempo.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Chi è {name}? L''unico/a essere vivente capace di sbagliare direzione in un corridoio a senso unico.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: certificato/a immune al sarcasmo. Ogni battuta viene presa alla lettera. Ogni volta. Senza mai imparare.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Vi presentiamo {name}: il/la tipo/a che cerca il senso della vita nel menu dei ristoranti.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: non è cattivo/a, è solo ottimizzato/a per il danno collaterale massimo con sforzo minimo.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Ecco {name}, il/la genio/a incompreso/a che nessuno ha capito perché oggettivamente c''è poco da capire.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: conosciuto/a per la capacità di trasformare qualsiasi successo in fallimento nel giro di 10 minuti esatti.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Chi è {name}? Il/la tipo/a che mette le proprie esigenze al primo posto. E al secondo. E al terzo. E così via.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: persona di larghe vedute. Peccato che le vedute siano tutte sistematicamente sbagliate.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Vi presentiamo {name}, l''unico/a membro del club "Ho ragione io" con zero soci soddisfatti.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: noto/a per parlare tanto e non dire mai niente che valga la pena ricordare il giorno dopo.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Ecco {name}, il/la portatore/trice cronico/a del complesso della vittima in ogni contesto non vittimistico.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: tecnicamente funziona. Nel senso che respira. Il minimo indispensabile.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Chi è {name}? Quello/a che nella riunione parla per 20 minuti senza arrivare al punto né avvicinarsi.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: ha tutte le caratteristiche del genio incompreso tranne quella fondamentale del genio.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Vi presentiamo {name}: il/la collega che scopre sempre di aver scelto il lavoro sbagliato dieci anni dopo.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: noto/a per avere opinioni fortissime su argomenti di cui non sa assolutamente niente.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Ecco {name}: presenza marginale, impatto minimo, ego al massimo storico. Equilibrio precario.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: specializzato/a nel trovare scuse per situazioni in cui bastava semplicemente chiedere scusa.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Chi è {name}? Il/la tipo/a che sbaglia la pizza quando ordina. Ogni volta. La stessa pizzeria. Da 5 anni.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: persona di successo nella dimensione parallela in cui vive e che nessun altro riesce a vedere.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Vi presentiamo {name}: il/la campione/ssa di "Avevo detto io" anche nei casi in cui non l''aveva detto.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: noto/a per essere il motivo per cui esistono le avvertenze sui prodotti elettronici.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Ecco {name}, il/la tipo/a che completa le frasi degli altri. Sempre in modo sbagliato. Con sicurezza.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: conosciuto/a localmente, ignorato/a globalmente, sopportato/a per pura cortesia formale.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Chi è {name}? Quello/a che porta il malocchio alle situazioni positive e buona fortuna a quelle già negative.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: tecnicamente capace di tutto. In pratica incapace di quasi tutto il tempo.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Vi presentiamo {name}: il/la tipo/a che manda vocali di 10 minuti per dire una cosa da 10 secondi.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: persona affascinante nel senso che ci si chiede costantemente come faccia a essere così persistentemente sbagliato/a.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Ecco {name}, professore/ssa emerito/a dell''Università del Niente, cattedra di Studi sull''Inutile.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: noto/a per avere un piano B anche per il piano B. Tutti e due falliscono invariabilmente.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Chi è {name}? Il/la tipo/a che dice "vado un secondo" e torna dopo 45 minuti senza spiegazioni.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: persona di grandi risorse personali. Completamente inesplorate. Per scelta deliberata.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Vi presentiamo {name}: il/la tipo/a che legge la fine del libro prima di iniziarlo e poi si lamenta del finale.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: capace di sembrare impegnato/a anche mentre non fa assolutamente niente di niente.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), 'Ecco {name}: il/la tipo/a che porta l''ombrello a Ferragosto e lo lascia a casa quando piove.'),
  ((SELECT id FROM categories WHERE slug = 'chi-e'), '{name}: una storia di vita che potrebbe essere un romanzo. Di quelli che si trovano nel cestino della libreria.');

-- ============================================================
-- 55 RISPOSTE AI LAMENTI
-- ============================================================

INSERT INTO text_responses (category_id, content) VALUES
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Ah poverino/a! Chiamo l''ambulanza o bastano i vigili del fuoco?'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Ti compatisco tantissimo. No aspetta, non è vero.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Eh, capita. Ma sinceramente non mi interessa.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Che tragedia cosmica! Vuoi che avvisi la Croce Rossa internazionale?'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Il tuo dolore mi tocca profondamente. Detto questo, me ne frego completamente.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Dio mio, che situazione terribile. Comunque, qualcuno ha visto il telecomando?'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Il tuo lamento è stato registrato e sarà ignorato entro 3-5 giorni lavorativi.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Tienimi aggiornato/a, ma da molto molto lontano.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Capisco il tuo disagio profondo. No, non è vero neanche stavolta.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Bello il tuo problema. Ne avrò uno simile mai nella vita.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Vuoi un violinista in sottofondo o preferisci piangerti addosso in silenzio dignitoso?'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'La vita è dura. Poi si muore. Buona fortuna nel frattempo.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Mi spezza il cuore. Che però è fatto di marmo per queste occasioni.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Nota la mia faccia di finta preoccupazione. Ci sto lavorando da ore.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Sono qui per te. Da questa parte dello schermo. Lontanissimo/a.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Il tuo problema è validissimo. Validissimamente non mio però.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Che sfortuna, amico/a mio/a. La vita ti vuole talmente bene che ti strozza.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Sto soffrendo per te. No, aspetta: sto sbadigliando. Mi confondo sempre.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Che bella notizia! Ah no, era un lamento. Mi sbaglio sempre con questi.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Hai bisogno di una spalla su cui piangere? Peccato che la mia sia in manutenzione.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Ti capisco profondamente. Come non capisco perché continui a lamentarti invece di fare qualcosa.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Ehilà! Benvenuto/a nel club "La vita fa schifo". Quota mensile: zero lacrime di coccodrillo.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Il tuo dramma personale è stato registrato nell''apposito cestino rosso dell''indifferenza.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Ah, la vita! Sempre così vigliaccamente viva, vero? Che seccatura.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Mi dispiace per te. Ma neanche troppo, per essere completamente onesti.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Grande problema epocale! Hai già chiamato il 112, 113, 115, 118 e Papa Francesco?'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Interessante. Adesso dimmi qualcosa che mi interessa davvero.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Capisco la tua sofferenza e la rispetto... da dietro una porta blindata.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Posso offrirti un momento di silenzio? Soprattutto il tuo silenzio.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Stai male? Prenditi una camomilla e smettila di rompere a tutti.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Sei stanco/a della vita? La vita è ancora più stanca di te, credimi.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Poverino/a! Quanto soffri. Ma soprattutto quanto fai soffrire gli altri con questo piagnisteo.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Hai bisogno di supporto emotivo? Ti mando un cuscino via Amazon Prime, arrivo in 24 ore.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Il tuo disagio è completamente comprensibile. E completamente insopportabile.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Ah, ti lamenti ancora! Che novità entusiasmante, eh? Come sempre.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Un consiglio non richiesto: smettila di lamentarti e fai qualcosa. Qualsiasi cosa. Anche alzarti.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Capisco. E con questo ho esaurito la mia empatia giornaliera. Quota finita.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Sei a pezzi? Gliene faccio un paio d''altri così almeno è completo.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'La vita ti ha deluso? Ti ha preso esattamente per quello che sei.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Coraggio! O almeno fai finta convincente. Meglio per tutti i presenti.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Stai soffrendo? Che carattere forte! Peccato che non cambi assolutamente niente.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Empatia mode: ON... nah, troppa fatica. OFF.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'La tua lamentela è stata ascoltata, valutata e classificata: irrilevante totale.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Sei triste? Mettiti una felpa, guarda YouTube e smetti di disturbare gli adulti.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Capisco il tuo stato d''animo. È una cosa tua però, tienilo.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Vorrei consolarti ma non ho il tempo, la voglia o la minima capacità in questo momento.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Dai, su! Potrebbe andare peggio. Probabilmente andrà peggio. Ma adesso potrebbe non farlo.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Il tuo sfogo è durato 3 minuti. La mia pazienza 45 secondi. Siamo matematicamente in debito.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Sai cosa ti farebbe bene? Non spetta a me dirtelo, ma sicuramente non è lamentarti.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Forza, che ce la fai! Ma non insistere troppo, che ce la fai benissimo anche da solo/a.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Quante energie spendi a lamentarti. Immagina se le usassi per qualcosa vagamente utile.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Ti do un consiglio: il problema che hai è esattamente tuo. Tienilo, non condividerlo.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Hai il coraggio di lamentarti qui? Rispetto. Mal riposto completamente. Ma rispetto.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Il tuo dramma merita un film. Di quelli che vanno direttamente su Netflix alle 3 di mattina.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Ho registrato la tua sofferenza. L''ho messa in cartella. La cartella è nel cestino.'),
  ((SELECT id FROM categories WHERE slug = 'lamenti'), 'Capisco che tu stia male. Stai male da prima che ti conoscessi. Ci siamo abituati tutti.');
