-- Migration 0008: necrologio, processo, cv, complimento, auguri, ego, segreto

INSERT INTO categories (name, slug, type) VALUES
  ('Necrologi', 'necrologio', 'text'),
  ('Processi', 'processo', 'text'),
  ('Curriculum Vitae', 'cv', 'text'),
  ('Complimenti', 'complimento', 'text'),
  ('Auguri', 'auguri', 'text'),
  ('Ego', 'ego', 'text'),
  ('Segreti', 'segreto', 'text');

-- ─── NECROLOGI ───────────────────────────────────────────────────────────────
INSERT INTO text_responses (category_id, content) VALUES
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'Si annuncia con qualche sollievo la dipartita di {name}. Causa: eccessiva stronzaggine cronica. Funerali: giovedì, se ricorda qualcuno.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), '{name} ci ha lasciati. Lascia un buco nella società più piccolo di quello che credeva di occupare.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'AVVISO FUNEBRE — {name} non c''è più. La notizia è stata accolta con un ''Oh'' e poi silenzio.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'Addio {name}. Hai vissuto poco e male ma almeno ora sei il problema di qualcun altro. Ciao.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), '{name} si è spento/a come uno smartphone senza carica: nel momento meno opportuno e senza preavviso.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'In memoria di {name}: nato/a per caso, vissuto/a per inerzia, morto/a per un motivo ancora da stabilire.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), '{name} ha raggiunto i suoi antenati. Gli antenati non erano entusiasti della cosa.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'È deceduto/a {name}, noto/a per aver sempre avuto ragione su tutto senza sapere niente di niente.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'La morte ha bussato alla porta di {name}. {name} ha aperto perché non capisce mai quando è meglio non farlo.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), '{name} ha chiuso gli occhi per sempre. Era l''unica cosa sensata che facesse.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'Riposa in pace {name}, che in pace non ha mai vissuto perché si lamentava sempre di tutto.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), '{name} è morto/a credendo di avere ancora molto da fare. Aveva da fare il bucato e chiamare la mamma.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'Si comunica con indifferenza la morte di {name}. I parenti si incontreranno per dividersi le cose.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), '{name} ha lasciato questo mondo con la stessa grazia con cui lo aveva attraversato. Inciampando.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'La salma di {name} sarà esposta per chi voglia darle un ultimo sguardo. Non è obbligatorio.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'Ciao {name}. Hai dato fastidio a molti, aiutato pochi, mangiato troppo. Riposa adesso.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'La morte è arrivata puntuale per {name}, a differenza di {name} che arrivava sempre tardi a tutto.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), '{name} è andato/a dove non si torna. Alcuni dicono sia un posto di pace. Reciproco.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'Ultima ora: {name} ha tirato le cuoia. Risposta del gruppo: ''Oh''. Poi silenzio.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'Si è spenta la fiamma di {name}. Era già abbastanza fioca in vita, quindi il cambiamento è stato impercettibile.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'Il gruppo WhatsApp di famiglia ha impiegato 3 giorni ad accorgersi che {name} non c''era. Indicativo.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'Neanche il tempo di capire cosa stava facendo della propria vita che {name} ha già smesso di farla.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), '{name} ha smesso di respirare. Era spesso l''unica cosa sensata che facesse.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'La comunità piange {name}. Non proprio piange. Ha preso nota e ha guardato i telefoni.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'In morte di {name}: non era il peggiore né il migliore. Era nel mezzo della mediocrità, e ci stava bene.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), '{name} ci ha abbandonati il giorno meno opportuno. Era fatto/a così: sempre nei momenti sbagliati.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'La famiglia annuncia con malcelato sollievo la scomparsa di {name}. La causa è ancora in discussione.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), '{name} ha smesso di esistere. Risposta del gruppo: ''Comunque, tornando a noi...'''),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'NECROLOGI — {name}: stroncato/a improvvisamente dalla propria stronzaggine cronica. Nessun testimone.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), '{name} riposa ora in pace. Era l''unica cosa che non sapeva fare da vivo/a. Speriamo ci riesca.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'Addio {name}. Il tuo contributo al progresso umano verrà ricordato durante le pause caffè, poi si cambierà argomento.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'La morte di {name} è arrivata come le sue idee: improvvisa, poco chiara e mal temprata.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), '{name} si è concluso/a. Era un capitolo breve, con poca trama e un finale prevedibile.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'Il Signore ha chiamato a sé {name}. Il Signore sa quello che fa? Speriamo.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'AVVISO FUNEBRE: {name} ha esalato l''ultimo respiro. Gli altri erano già stati abbastanza pesanti.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), '{name} è morto/a come aveva vissuto: senza preavviso e creando disagio agli altri.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'Si è spento/a {name}, lasciando un''eredità spirituale di circa 300 messaggi in chat che nessuno rileggeva.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'I funerali di {name} si terranno quando qualcuno si ricorderà di organizzarli.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), 'Ciao {name}. Nella vita hai fatto tante cose. Alcune erano anche lecite. Arrivederci.'),
  ((SELECT id FROM categories WHERE slug = 'necrologio'), '{name} ci mancherà come manca il mal di denti: non si sente la mancanza, ma ci si ricorda.');

-- ─── PROCESSI ────────────────────────────────────────────────────────────────
INSERT INTO text_responses (category_id, content) VALUES
  ((SELECT id FROM categories WHERE slug = 'processo'), 'IL TRIBUNALE SBORRBOT DICHIARA {name} COLPEVOLE di essere insopportabile. Condanna: scusarsi con tutti quelli che ha incontrato nella vita.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'SENTENZA — {name}: colpevole di cretineria premeditata. Pena: 5 anni di silenzio obbligatorio. Non è ammesso ricorso.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), '{name} è stato/a giudicato/a colpevole di tutte le accuse. Alcune non erano neanche nel capo d''imputazione originale.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'Il PM ha definito {name} un pericolo per l''equilibrio del gruppo. La corte ha concordato. Condannato/a.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'VERDETTO UNANIME — {name}: colpevole. Il giudice aveva già deciso prima che aprisse la bocca. Poi l''ha aperta e ha avuto ragione.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'La corte condanna {name} a pagare una multa in dignità. Non avendola, la pena è sospesa per insolvenza.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'SENTENZA N.420 — {name}: colpevole di mediocrità volontaria. Pena: essere esattamente quello/a che è già.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'La difesa di {name} ha sostenuto che era una brava persona. La corte ha preso atto e l''ha condannato/a lo stesso.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'Processo a {name}: colpevole di mandare vocali di 7 minuti quando bastava un testo. Pena: 3 anni senza microfono.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), '{name}: colpevole di aver detto "in realtà" all''inizio di ogni frase per 15 anni. Pena: esame di coscienza.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'La giuria composta da 12 persone ha guardato {name} e ha detto no. Unanimità totale. Colpevole su tutti i fronti.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'SBORRBOT JUSTICE — {name}: colpevole di esistere in modo esasperante. Reato creato apposta per lui/lei.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'Caso {name}: colpevole di aver raccontato lo stesso aneddoto per la quarta volta in sei mesi. Pena: divieto di narrare per 2 anni.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'La testimonianza di {name} in propria difesa ha peggiorato significativamente la sua posizione. Condannato/a con aggravanti.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'VERDETTO — {name}: colpevole di postare foto di cibo al ristorante per 8 anni consecutivi. Pena: mangiare solo in solitudine.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'Il Giudice ha letto le prove contro {name} e ha detto solo "Madonna". Poi ha firmato la condanna senza aggiungere altro.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'SENTENZA — {name}: colpevole di vittimismo prolungato. Condannato/a a stare bene per 30 giorni senza lamentarsi.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'PROCESSO SOMMARIO — {name}: colpevole di tutto ciò che viene in mente. La corte non ha voglia di dettagliare. Ergastolo morale.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'Reato contestato a {name}: aver lasciato "visto" senza rispondere per 3 giorni. Pena: rispondere entro 10 minuti per sempre.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'Il Giudice Impepato-Merli sentenzia: {name} colpevole di arroganza senza base. Pena: guardare le proprie foto del 2012.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'VERDETTO FINALE — {name}: colpevole di tutto tranne ciò che pensava di avere fatto. Paradossalmente peggio.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'La corte di SborrBot si è riunita per giudicare {name} e si è sciolta 5 minuti dopo avendo già deciso. Tempi record.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), '{name}: condannato/a a 3 anni di umiltà forzata. Non è commisurata al reato ma è quello che c''è.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'Per anni di crimini cumulativi contro la pazienza delle persone, {name} è condannato/a all''ergastolo morale.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'SENTENZA — {name}: colpevole di monopolio della conversazione. Pena: ascoltare gli altri per 1 anno. Pena minima.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'Il Tribunale Superiore di SborrBot condanna {name} per crimini di mediocrità premeditata. Appello: zero possibilità.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'Reato di {name}: credere che la sua opinione fosse importante. Pena: silenzio riflessivo a tempo indeterminato.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'La corte non ha trovato attenuanti per {name}. Ne ha cercate. Gliele hanno suggerite. Non ce n''erano. Colpevole.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'GIUDIZIO FINALE — {name}: colpevole. Non serve motivazione. Basta parlare con chiunque lo/la conosca 10 minuti.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), '{name}: condannato/a per aver usato "comunque" e "in effetti" nello stesso messaggio. La corte non tollera.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'SBORRBOT CORTE SUPREMA — {name}: colpevole di dire "sono fatto così" come giustificazione. Non funziona. Condannato/a a cambiare.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'Il PM ha presentato 47 prove contro {name}. La difesa le ha contestate. La corte le ha ignorate e l''ha condannato/a lo stesso.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'Per il crimine di noia cronica, {name} è condannato/a a non parlare per 6 mesi. La corte si complimenta per il ritrovato silenzio.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'La sentenza definitiva: {name} è condannato/a ad ammettere di avere torto almeno una volta. La corte augura buona fortuna.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'PROCESSO PER DIRETTISSIMA — {name}: colpevole. Già deciso prima dell''udienza. L''udienza era una formalità.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'Il crimine di {name}: credere che le sue storie interessassero. Danno incommensurabile. Ergastolo spirituale.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'La corte ha analizzato la vita di {name} e ha trovato numerosi reati minori accumulati nel tempo. Condannato/a per il totale.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'SENTENZA NUMERO FINALE — {name}: colpevole di esistere in modo esasperante. Non è codificato ma la corte lo ha creato.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'La giuria ha deliberato in 40 secondi. Il processo è durato più perché {name} voleva spiegare. Non ha aiutato.'),
  ((SELECT id FROM categories WHERE slug = 'processo'), 'Giudice Merda-Bianchi sentenzia: "{name}: colpevole. Prossimo." E se n''è andato. Tempi record.');

-- ─── CURRICULUM VITAE ────────────────────────────────────────────────────────
INSERT INTO text_responses (category_id, content) VALUES
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CURRICULUM — {name}: Formazione: licenza media al terzo tentativo. Esperienza: 3 mesi parcheggiatore abusivo, licenziato/a per eccessiva iniziativa. Referenze: nessuna.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CV — {name}: Ultimo impiego: stagista non retribuito/a presso lo zio. Motivo fine rapporto: problemi di carattere. Ambizioni: diventare influencer.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), '{name} | PROFILO: Obiettivo professionale: fare qualcosa che piaccia e paghi bene senza troppo stress. Qualifiche: attestato di cucina non terminato (2017).'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CURRICULUM DI {name}: Studi: università iscritta nel 2016, ancora in corso. Lavori: 4 in 2 anni, tutti finiti per accordo reciproco.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), '{name} — ESPERIENZA: 2018: startup fallita in 4 mesi. 2020: freelance mai pagato/a. 2021-oggi: disoccupato/a "per scelta".'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CURRICULUM — {name}: Titolo di studio: "esperto/a di vita" (autodichiarato). Lingue: italiano (incerto). Referenze: genitore.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CV — {name}: Competenze: Excel apre il file. PowerPoint sa dov''è il tasto. Lingue straniere: qualche parolaccia in inglese.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), '{name} | CV: Disponibilità: dipende dall''umore. Salario richiesto: fuori mercato. Note: richiede parcheggio gratuito e non lavora il venerdì.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CURRICULUM — {name}: Soft skills: empatia non testata, resilienza non testata, leadership fortemente testata e smentita sul campo.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), '{name} — CV 2025: Objective: voglio fare una cosa bella che paghi bene senza stress. Education: ho guardato molti documentari. Skills: ChatGPT.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CV DI {name}: Formazione: YouTube University, corso mindfulness al 34%, podcast di crescita personale non finiti.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CURRICULUM — {name}: 6 lavori in 5 anni. Motivi di uscita: atmosfera tossica (x3), mancanza stimoli (x2), problemi col capo (x1).'),
  ((SELECT id FROM categories WHERE slug = 'cv'), '{name} | PROFESSIONAL SUMMARY: 1 anno e mezzo di niente formattato bene. Skill endorsate da sua madre: 7. Connessioni LinkedIn: 84, di cui conosce 12.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CV — {name}: Note del selezionatore: bella impaginazione, contenuto scarso. Archiviato nella cartella "forse" da 8 mesi senza essere riaperto.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CURRICULUM — {name}: Lingue: italiano madrelingua, inglese B1 dichiarato A2 reale, francese "qualcosa ricordo".'),
  ((SELECT id FROM categories WHERE slug = 'cv'), '{name} | CV: Specializzazione: problem solving. Problemi effettivamente risolti in carriera: da 0 a 2, ancora in discussione.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CURRICULUM — {name}: Stage da 400 euro al mese, rinnovato per altri 6 mesi a 350. Non ha capito il messaggio. Ora ne fa un altro.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), '{name} — CV: Caratteristiche: puntuale a volte, motivato/a quando conviene, disponibile se non ha altro. Punti deboli: tutto il resto.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CV — {name}: Foto allegata al CV: non era una buona idea. Al colloquio ha parlato 40 minuti di sé senza rispondere a nessuna domanda.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CURRICULUM — {name}: Ambizioni: vaghe. Forza caratteriale: da verificare. Note del recruiter: portare referenze se ne trova.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), '{name} | CURRICULUM: Esperienza manageriale: ha coordinato un team di 3 persone per un progetto. Il team erano i coinquilini. Il progetto: montare un mobile IKEA.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CV — {name}: Ha risposto solo ai colloqui con buffet. Richiede smart working al primo colloquio. Non ha portato documenti nonostante richiesta esplicita.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CURRICULUM — {name}: GitHub esiste ma è vuoto. Portfolio: link non funzionante. Si definisce "developer". JavaScript "ci sto lavorando da 3 anni".'),
  ((SELECT id FROM categories WHERE slug = 'cv'), '{name} — CURRICULUM: Laurea in Giurisprudenza, anno 7, in "completamento". Tesi: titolo cambiato 3 volte. Relatore: ha smesso di rispondere alle mail.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CV — {name}: Passioni: viaggi guardati su Instagram, cucina (ordina spesso), lettura (un libro all''anno se va bene).'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CURRICULUM — {name}: Punto di forza al colloquio: "sono una persona solare". Dove si vede tra 5 anni: "non lo so, onestamente". Referenza: genitore.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), '{name} | CV: Pretese salariali: non meno di quello che guadagna il cugino. Flessibilità: sì ma non il mattino e non il venerdì.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CURRICULUM — {name}: Core competency principale: delegare, rimandare, trovare scuse creative. Referenze: disponibili solo da parenti di primo grado.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CV — {name}: Follow-up ogni 3 giorni nonostante silenzio assoluto da parte dell''azienda. Disponibilità immediata: sì, non ha di meglio.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), '{name} — CURRICULUM: Sezione hobby: lettura 1 libro/anno, sport (teoria), Erasmus Siviglia 2018. Skill acquisite: resistenza ai cicchetti.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CURRICULUM — {name}: Domanda al colloquio: "Perché dovremmo sceglierla?" Risposta: silenzio di 8 secondi, poi "sono molto motivato/a".'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CV — {name}: Brand personale: in costruzione dal 2019. Network: amici al bar + 84 contatti LinkedIn mai attivati. Influenza: nulla.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CURRICULUM — {name}: Titolo autoassegnato: "team leader". Prove: nessuno lo/la ha mai ascoltato/a in vita sua.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), '{name} | CV: Caratteristica principale: ottimismo inesplicabile data la situazione. Il selezionatore ha apprezzato. Non è stato richiamato/a.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CV — {name}: Certificazioni: attestato primo soccorso scaduto 2019, sicurezza sul lavoro (obbligatorio, mai ripassato, probabilmente inutile).'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CURRICULUM — {name}: Molto curriculum, poca vita. Bella impaginazione, contenuto scarso. Non si vede bene in prospettiva.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), '{name} — CV: Il candidato/a ha una visione ma non un piano. Ha risposto "ce la metto tutta" a tutte le domande del colloquio.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CURRICULUM — {name}: Insiste per incontrare direttamente il CEO al primo colloquio. Il CEO non è disponibile. Non era mai disponibile.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CV — {name}: Esperienza più lunga: 14 mesi come magazziniere. Uscito/a per "riduzione del personale". Era l''unico/a dipendente.'),
  ((SELECT id FROM categories WHERE slug = 'cv'), 'CURRICULUM — {name}: Ha usato 3 font diversi nel CV. Foto in bianco e nero con aria seria. Evidentemente nessuno glielo ha detto. Non aiuta.');

-- ─── COMPLIMENTI ─────────────────────────────────────────────────────────────
INSERT INTO text_responses (category_id, content) VALUES
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Sei davvero in gamba, {name}. Per uno/a con così poche possibilità di partenza hai fatto discretamente poco.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), '{name}, riesci a dire cose sbagliate con una sicurezza che quasi convince. È un talento raro.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Sei bellissimo/a, {name}. Specie di mattina, prima di aprire la bocca.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Ho grande rispetto per te, {name}. Ci vuole coraggio a essere così e mostrarsi in pubblico.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), '{name}, sai fare moltissime cose. Peccato che nessuna sia particolarmente utile.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Hai un''intelligenza tutta tua, {name}. Non è quella convenzionale ma è definitivamente tua.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Sei l''unico/a che conosco capace di sbagliare anche le cose facili, {name}. Quasi un talento.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Sei genuino/a, {name}. Non fai finta di essere intelligente. Sincero almeno.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Hai il dono della semplicità, {name}. Molto, molto semplice.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Sei molto creativo/a nel trovare scuse, {name}. È un tipo di creatività, tecnicamente.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Sei sempre molto presente, {name}. Non sempre utile ma presente sì.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Hai un cuore grandissimo, {name}. Il cervello è più piccolo ma il cuore è enorme.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Sei ottimista, {name}. Inesplicabilmente, data la situazione, ma ottimista.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Sei simpatico/a, {name}. Almeno tu lo pensi e conta qualcosa.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Hai una visione unica delle cose, {name}. Il che significa che nessun altro la condivide, ma è comunque una visione.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), '{name}, la tua dedizione è ammirevole. A cosa la applichi è ancora da capire, ma c''è.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Sei molto diretto/a, {name}. Forse un po'' troppo ma apprezzo l''impegno.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), '{name}, hai una resilienza notevole. Quante delusioni hai subito e sei ancora lì. Impressionante.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Sei autentico/a, {name}. Non filtri niente, nel bene e nel male. Soprattutto nel male.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), '{name}, sei un esempio per tutti. Di come non bisogna fare alcune cose. Ma pur sempre un esempio.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Sei molto empatico/a, {name}. Peccato che l''empatia funzioni a senso unico.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Hai il coraggio delle tue opinioni, {name}. Il problema sono le opinioni stesse.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), '{name}, sei molto preciso/a nelle cose che non contano niente.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Hai una grande capacità di ascolto, {name}. Peccato non ricordi niente di quello che senti.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Sei carismatico/a a modo tuo, {name}. Il tuo modo è un po'' particolare ma è il tuo.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), '{name}, hai imparato molto dalla vita. Forse non le lezioni giuste ma hai imparato qualcosa.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Sei generoso/a, {name}. Distribuisci problemi e pensieri a tutti con grande liberalità.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Sei molto attento/a ai dettagli, {name}. Specialmente a quelli irrilevanti.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Hai una grande immaginazione, {name}. La usi principalmente per preoccuparti, ma c''è.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), '{name}, sei motivato/a. Non sempre verso gli obiettivi giusti ma c''è la motivazione.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Sei molto comunicativo/a, {name}. In quantità, non necessariamente in qualità.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Hai uno stile tutto tuo, {name}. Non è per tutti ma è coerente con te stesso/a.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Sei molto curioso/a, {name}. Su argomenti che non servono a niente ma sei curioso/a.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Hai una grande forza di carattere, {name}. La usi per difendere posizioni indifendibili.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), '{name}, sei una persona di principi. Principi tutti tuoi, condivisi da nessun altro.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Sei molto ambizioso/a, {name}. Più delle tue capacità attuali, diciamo, ma l''ambizione c''è.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), '{name}, riesci a rendere anche le situazioni semplici complicatissime. Non è facile.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Sei molto intuitivo/a, {name}. Quasi tutte le tue intuizioni sono sbagliate ma arrivano veloce.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), 'Hai un ottimo senso del ritmo, {name}. Peccato per tutto il resto.'),
  ((SELECT id FROM categories WHERE slug = 'complimento'), '{name}, sei coraggioso/a. Pochissimi parlerebbero così con quella preparazione sull''argomento.');

-- ─── AUGURI ──────────────────────────────────────────────────────────────────
INSERT INTO text_responses (category_id, content) VALUES
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Auguri del cazzo. Un altro anno di sfiga ti aspetta.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Buon compleanno! Ogni anno che passa sei più vecchio/a e non migliori. Festeggia.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Auguri. Stai invecchiando. Non c''è molto altro da aggiungere.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Tanti auguri! Che questo anno sia leggermente meno di merda del precedente.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Buon compleanno! Il tuo fegato ti manda i saluti e chiede di rallentare.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Auguri! Un anno in più, nessun progresso significativo. Tradizione rispettata.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Congratulazioni per non essere morto/a. Bassa asticella ma risultato.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Le candeline sulla torta aumentano, le scuse diminuiscono. Auguri.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Buon compleanno! Oggi hai un anno in più per pentirti delle stesse cose.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Auguri! Speriamo che quest''anno tu faccia almeno una cosa utile. Bassa aspettativa.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Buon compleanno! Altro giro, altra corsa verso nessuna parte precisa.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Auguri di cuore (quello che ti rimarrà dopo gli anni che ti aspettano).'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Buon compleanno! Festeggi oggi. Domani tutto come prima. Goditi le 24 ore.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Tanti auguri, che tu possa avere tutto quello che ti meriti. Senza esagerare però.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Buon compleanno! Le candeline si moltiplicano. Il senno no.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Auguri! L''anno scorso eri giovane. Quest''anno sei solo meno giovane. La tendenza è chiara.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Buon compleanno! Spegni le candeline e fai un desiderio assurdo come sempre.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Auguri. Il compleanno è una volta all''anno. La delusione è quotidiana. Non si può vincere tutto.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Buon compleanno! Festeggia pure, che domani è lunedì.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Auguri! Che la torta sia buona perché il resto dell''anno non lo garantiamo.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Tanti auguri! Un anno in più di vita. Non sprecarli come stai facendo finora.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Buon compleanno a te, che non sai ancora cosa ti aspetta. E meno male.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Auguri! Invecchi ma non cresci. Almeno sei costante.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Buon compleanno! Che quest''anno tu capisca almeno una cosa che l''anno scorso non capivi.'),
  ((SELECT id FROM categories WHERE slug = 'auguri'), 'Tanti auguri di tutto cuore. La torta è buona ma la vita è più amara. Buona fortuna.');

-- ─── EGO ─────────────────────────────────────────────────────────────────────
INSERT INTO text_responses (category_id, content) VALUES
  ((SELECT id FROM categories WHERE slug = 'ego'), 'Sei il migliore? Di cosa esattamente? E rispetto a chi? Specifica, dai.'),
  ((SELECT id FROM categories WHERE slug = 'ego'), 'Certo che sei forte. Anche le cipolle fanno piangere ma non le rispettiamo per questo.'),
  ((SELECT id FROM categories WHERE slug = 'ego'), 'Bravo/a dai. Continua così e un giorno magari diventi anche utile.'),
  ((SELECT id FROM categories WHERE slug = 'ego'), 'Il migliore? Abbassa l''asticella e vedrai che è meno difficile.'),
  ((SELECT id FROM categories WHERE slug = 'ego'), 'Forte? Nel senso che puzzi forte. Ma celebriamo anche questo.'),
  ((SELECT id FROM categories WHERE slug = 'ego'), 'Bravissimo/a! Principalmente a convincerti di cose non verificate.'),
  ((SELECT id FROM categories WHERE slug = 'ego'), 'Il migliore. Certo. Adesso raccontaci dell''altra volta.'),
  ((SELECT id FROM categories WHERE slug = 'ego'), 'Bravo/a! Ogni tanto capita anche ai migliori. E anche a te.'),
  ((SELECT id FROM categories WHERE slug = 'ego'), 'Sei forte. Resistenza alla realtà di tipo olimpionico.'),
  ((SELECT id FROM categories WHERE slug = 'ego'), 'Il migliore del gruppo? Il gruppo si è offeso ma vabbè.'),
  ((SELECT id FROM categories WHERE slug = 'ego'), 'Bravo/a! Ti do un punto. Ne mancano molti per qualcosa di concreto ma un punto ce l''hai.'),
  ((SELECT id FROM categories WHERE slug = 'ego'), 'Sei il migliore. Dillo ancora finché ci credi tu stesso/a.'),
  ((SELECT id FROM categories WHERE slug = 'ego'), 'Forte! Tipo quanto? Ho dei parametri da rispettare prima di congratularmi.'),
  ((SELECT id FROM categories WHERE slug = 'ego'), 'Sei bravissimo/a a fare cose che fai già da anni. Progresso zero ma maestria sì.'),
  ((SELECT id FROM categories WHERE slug = 'ego'), 'Il migliore della categoria "io stesso/a a valutarsi". Record personale.'),
  ((SELECT id FROM categories WHERE slug = 'ego'), 'Certo che sei bravo/a. Anche il tuo gatto lo pensa. Il gatto sbaglia spesso.'),
  ((SELECT id FROM categories WHERE slug = 'ego'), 'Sei il migliore. Ok. Tienitelo. È gratis.'),
  ((SELECT id FROM categories WHERE slug = 'ego'), 'Bravo/a! Però non dirlo in pubblico che poi ti chiedono di dimostrarlo.'),
  ((SELECT id FROM categories WHERE slug = 'ego'), 'Il migliore! Campione del mondo di autostima non basata su dati oggettivi.'),
  ((SELECT id FROM categories WHERE slug = 'ego'), 'Sei il migliore. Adesso fallo. Sul serio. Aspetto.');

-- ─── SEGRETI ─────────────────────────────────────────────────────────────────
INSERT INTO text_responses (category_id, content) VALUES
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Si sussurra nei vicoli che una notte di novembre {name1} e {name2} hanno fatto cose che neanche il più coraggioso dei giornalisti investigativi oserebbe pubblicare. Coinvolti: lardo di Colonnata, una carriola e tre testimoni che hanno giurato il silenzio.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Secondo fonti anonime, {name1} e {name2} hanno trascorso un pomeriggio di luglio in circostanze che la magistratura definisce ambigue e i presenti definiscono indicibili. Le autorità non indagano perché preferiscono non sapere.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'È noto nell''ambiente che {name1} ha una relazione torbida con {name2} che dura da 3 anni. La relazione comprende cose che si fanno solo di notte, in silenzio, dopo aver chiuso le finestre.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Un testimone racconta: quella sera {name1} e {name2} sono entrati in cantina portando una borsa. Sono usciti tre ore dopo, senza borsa, con espressioni soddisfatte e un''intesa silenziosa che durerà per sempre.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Si dice che {name1} e {name2} abbiano un codice segreto: quando uno scrive "papavero" l''altro capisce. Nessuno ha ancora capito cosa voglia dire. Forse è meglio così.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'La verità che tutti fingono di non sapere: {name1} ha visto {name2} in una situazione che non si descrive con le parole. {name2} lo/la sa. Da quel giorno si guardano con quell''intesa che nasce solo dal disagio condiviso.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Secondo il barista del Gallo Ubriaco, {name1} e {name2} si incontrano ogni primo martedì del mese. Cosa fanno? Il barista ha smesso di fare domande dopo la seconda volta.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il segreto di {name1} e {name2}: quella notte di capodanno del 2022 di cui nessuno parla. Erano in cinque. Ora sono rimasti in due. Gli altri tre si sono trasferiti in città diverse e non rispondono alle chiamate.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Fonti attendibili confermano che {name1} e {name2} hanno condiviso qualcosa di intimo e macabro dietro il cimitero del paese, di giovedì, in ottobre. I dettagli verranno portati nella tomba. Letteralmente.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), '{name1} custodisce un segreto su {name2} che potrebbe distruggere reputazioni, matrimoni e almeno due carriere. {name2} lo sa. Per questo si sorridono sempre quando si vedono, con quel sorriso di chi ha troppe informazioni.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Secondo un documento di dubbia provenienza, {name1} e {name2} sono stati fotografati in un motel della provinciale nel 2023. Le foto esistono ancora. Nessuno dei due sa dove. Ma esistono.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'La storia che circola: {name1} ha aiutato {name2} a nascondere qualcosa nell''estate del 2021. Non si sa cosa. Si sa solo che entrambi hanno comprato guanti di gomma lo stesso giorno.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Si mormora che {name1} e {name2} condividano una cassetta di sicurezza in Svizzera contenente materiale che la società civile non è pronta ad affrontare. Il numero della cassetta: 7.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il segreto peggio custodito del gruppo: {name1} e {name2} credono che nessuno sappia. Invece sanno tutti. Ma nessuno vuole essere il primo a dirlo.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Testimoni oculari riferiscono di aver visto {name1} e {name2} uscire alle 4 di mattina da un appartamento che non apparteneva né all''uno né all''altro, ridendo di qualcosa che non avrebbe dovuto essere divertente.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il medico di base di {name1} ha incrociato per caso {name2} e ha avuto un''espressione strana. Ha solo detto "capisco tutto adesso" e ha cambiato argomento. Da quel giorno la cosa ha un nome ma il nome non si pronuncia.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Secondo il vicinato, {name1} visita {name2} ogni volta che piove. Non si sa perché solo quando piove. Non si è mai voluto indagare.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'La storia macabra: {name1} e {name2} hanno trovato qualcosa durante una gita fuori porta nel 2020. Non hanno chiamato la polizia. Si sono guardati, hanno annuito, e hanno continuato a camminare.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Risulta da conversazioni intercettate che {name1} chiama {name2} con un soprannome che, tradotto dal dialetto locale, significa qualcosa di profondamente inappropriato. {name2} risponde senza battere ciglio.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Tutti sanno ma nessuno dice: {name1} e {name2} hanno una chat su un''app criptata che si cancella ogni 24 ore. Il nome della chat è "Riunione di lavoro".'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il prete della parrocchia ha detto a {name1}: "figlio/a mia, per quello che hai fatto con {name2} ci vorrà più di tre Ave Maria". Non ha specificato quante di più. La cosa è rimasta aperta.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Una fonte anonima descrive una scena a cui ha assistito involontariamente: {name1} e {name2}, una porta semi-aperta, qualcosa che sembrava una cerimonia ma non era una cerimonia. Chi ha visto non dorme più tranquillo/a.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Si dice che {name1} abbia tatuato il nome di {name2} in un posto che si può mostrare solo in tre circostanze specifiche. Due delle tre si verificano raramente. La terza si è già verificata.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), '{name1} e {name2} si sono scambiati delle informazioni su di sé che, se diventassero pubbliche, costringerebbero entrambi a cambiare città, nome e taglio di capelli.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il direttore dell''oratorio ricorda quella serata di charity: {name1} e {name2} si sono offerti di sistemare le cantine. Ci hanno messo cinque ore per un lavoro da quaranta minuti. La cantina non era mai stata così silenziosa.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Negli archivi della biblioteca comunale risulta che {name1} e {name2} hanno preso in prestito lo stesso libro nello stesso periodo. Il libro si intitola "Pratiche avanzate". Il codice Dewey è in una sezione che la bibliotecaria preferisce non citare.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'La cartolina trovata in un cassetto, indirizzata a {name1}: "quello che abbiamo fatto in quel B&B non si racconta. Si porta con sé. Come ho intenzione di fare." Firmato: {name2}. P.S.: cancella anche tu la chat.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il nipote di {name1} racconta: da piccolo ho aperto la porta di una stanza e ho visto {name1} e {name2} fare qualcosa. Mi è stato detto che stavano giocando a scacchi. Avevo sei anni e già sapevo.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Fonti dal quartiere confermano che {name1} e {name2} si incontrano ogni anno lo stesso giorno nello stesso posto. Il posto non è un posto normale. La cosa che fanno lì non è una cosa normale.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il tatuatore locale rivela: ho fatto un tatuaggio a {name1} con su scritto qualcosa in codice. Poi è arrivato/a {name2} e ha detto "capisco". È uscito/a sorridendo. Non ho chiesto spiegazioni.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Una lettera anonima recapitata al sindaco: "{name1} e {name2} si incontrano regolarmente e fanno cose che non sono illegali ma che andrebbero quantomeno discusse in sede di consiglio comunale." La lettera è rimasta senza risposta.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il carabiniere in pensione del paese afferma: "li ho tenuti d''occhio, {name1} e {name2}. Non c''era niente di penalmente rilevante. Ma ci voleva poco. Molto poco."'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), '{name1} e {name2} si scambiano messaggi con emoji che non significano quello che significano normalmente. L''emoji della melanzana, in questo contesto, ha un significato completamente diverso.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il cugino di {name2} racconta: ho trovato per sbaglio una lista scritta da {name1}. Era una lista di cose da fare. Ho rimesso la lista al suo posto e non ho dormito quella notte.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Quella sera di capodanno {name1} e {name2} si sono guardati attraverso la stanza per venti minuti senza dirsi niente. Poi {name1} ha alzato le sopracciglia. {name2} ha annuito. Sono usciti insieme. Non sono tornati alla festa.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il frate del convento vicino ricorda: "una volta mi hanno chiesto di benedire qualcosa che portavano in una borsa. Dalla benedizione che mi hanno chiesto ho capito che era meglio non guardare dentro."'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), '{name1} possiede una chiavetta USB criptata che contiene materiale su {name2}. {name2} possiede una chiavetta identica con materiale su {name1}. È il loro patto di non aggressione. Funziona.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il segreto che tutti fingono di non avere sentito: {name1} ha raccontato in confidenza a un amico cosa aveva fatto con {name2}. L''amico ha aggiunto solo "dio mio". Ora lo sa tutto il quartiere.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il diario di bordo di una barca a noleggio del Lago di Como riporta: "{name1} e {name2}, notte tra il 12 e il 13 agosto, barca riportata con 3 ore di ritardo, ancora ammaccata, nessuna spiegazione."'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il custode del cimitero racconta: "li ho visti passeggiare tra le tombe di sera, {name1} e {name2}. Non so cosa ci facessero. Sembravano a casa loro. Più di me."'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Secondo il dermatologo: "ho visitato {name1} per alcuni segni particolari. Mi ha detto che erano di {name2}. Ho annotato in cartella: causa esterna, natura consensuale, non procedere oltre."'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'La portieria del condominio di {name2}: "sento tutto. Quello che succede quando c''è {name1} non ha una categoria linguistica appropriata. Ho comprato dei tappi per le orecchie."'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), '{name1} e {name2} si sono scambiati qualcosa di personale durante una cena di gruppo. Lo scambio è avvenuto sotto il tavolo. Nessuno ha visto. Tutti hanno percepito.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il medico veterinario che segue il gatto di {name1} rivela: "{name2} porta il gatto alle visite quando {name1} non può. Sa tutto: dieta, vaccini, comportamenti. Sa anche altre cose. Lo si capisce dallo sguardo."'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Una mail in bozze mai inviata, sul computer di {name1}: "Oggetto: proposta. Quella cosa che abbiamo fatto a Pasqua, possiamo rifarlo a Ferragosto? Non per forza in Puglia. Ma con lo stesso... equipaggiamento."'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il fotografo del matrimonio di un conoscente: "{name1} e {name2} erano tra gli invitati. Nelle foto ufficiali sono composti. Nelle foto casuali c''è una sequenza che ho consegnato in una busta separata solo a loro."'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Fonte da ambienti ecclesiastici: è stata presentata formalmente una richiesta di esonero dalla confessione per {name1}. Il motivo: "quello che succede con {name2} è una situazione troppo complessa per la liturgia ordinaria."'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il barman ricorda: {name1} e {name2} hanno ordinato la stessa cosa senza parlarsi. Si sono seduti lontani. Poi uno dei due ha scritto un messaggio. L''altro l''ha letto. Si sono alzati insieme. Quello sguardo non lo dimentico.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Risulta agli atti che {name1} e {name2} abbiano condiviso un appartamento per 11 giorni nel 2021, "per lavoro". Il proprietario ha detto: "non so cosa abbiano combinato ma il materasso va sostituito."'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il nipote di {name2} ha trovato in soffitta una scatola con oggetti di {name1} e lettere non spedite. Ha rimesso tutto a posto. Non ha detto niente a nessuno. Ha però cambiato il modo in cui guarda gli adulti.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Nel libro degli ospiti di un agriturismo: "{name1} e {name2}: un fine settimana che ha ridefinito alcuni concetti fondamentali." L''agriturismo li ha nella lista nera perché l''ultima volta la cucina richiedeva un esorcismo.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il medico di guardia: "si sono presentati insieme, {name1} e {name2}. Erano troppo coesi nel racconto, come chi ha avuto molto tempo per allineare la versione. Ho scritto in cartella: causa: attività ricreativa intensa."'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), '{name1} e {name2} hanno un rituale che dura dalle 11 di sera alle 3 di mattina. Non si sa cosa comprenda. Si sa che il giorno dopo arrivano in ritardo ovunque, con un''aria soddisfatta e una lieve andatura asimmetrica.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il segreto finale: {name1} sa di {name2} una cosa che {name2} pensa di tenere nascosta. {name2} sa di {name1} una cosa che {name1} pensa di tenere nascosta. Sono in stallo da anni. L''equilibrio regge. Per ora.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Indiscrezioni dal quartiere: {name1} e {name2} sono stati visti comprare le stesse cose al supermercato in momenti diversi della stessa giornata. La lista della spesa era identica. Nessuno ha commentato. Tutti hanno capito.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'La testimonianza del vigile del fuoco intervenuto: "quando siamo arrivati c''erano {name1} e {name2}. Ci hanno detto che era un incidente domestico. Tecnicamente non mentivano. Ma tecnicamente neanche dicevano tutto."'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Un''intercettazione accidentale: {name1} stava descrivendo a qualcuno quello che {name2} gli/le fa. La descrizione durava 4 minuti. La persona che ascoltava ha interrotto al secondo minuto e ha detto "ok, ho capito abbastanza".'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'La storia che nessuno racconta per intero: esiste un video. Non è pubblicabile. È nelle mani di {name1} e {name2} e di nessun altro. Il fatto che esistano entrambe le copie garantisce un equilibrio di terrore reciproco.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Secondo l''idraulico intervenuto a casa di {name2}: "mi ha aperto {name1}. Erano le 10 di mattina di mercoledì. Nessuno dei due ha spiegato niente. Ho sistemato il tubo e sono andato via molto velocemente."'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il segreto che il gruppo porta da anni: esiste una foto di {name1} e {name2} in una situazione che, se circolasse, cambierebbe per sempre le dinamiche di ogni interazione sociale futura.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Secondo un''analisi grafologica della corrispondenza, {name1} e {name2} si scrivono da anni con una grafia diversa da quella normale. Gli esperti definiscono le lettere "intensamente personali". Il resto non è analizzabile.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il commercialista di {name1} ha incrociato {name2} per caso in uno studio notarile. Nessuno dei due doveva essere lì. Non si sono detti niente. Si sono guardate le mani. Poi sono usciti da porte diverse.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'La storia dei tre oggetti: {name1} ha qualcosa che appartiene a {name2}, {name2} ha qualcosa che appartiene a {name1}, e nessuno dei due fa mai menzione dello scambio. Eppure sanno entrambi esattamente di cosa si tratta.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Una fonte ospedaliera riporta che {name1} e {name2} si sono presentati insieme al pronto soccorso nel luglio 2023. La diagnosi è coperta da segreto professionale. Il medico di turno ha chiesto trasferimento la settimana dopo.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il vecchio del bar che sa tutto racconta: "quella notte ho visto uscire {name1} e {name2} dalla parrocchia alle 2. La parrocchia era chiusa. Da trent''anni non mi meraviglio più di niente. Quella notte quasi."'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), '{name1} sa dov''è il corpo. Non di una persona, non necessariamente. Ma sa dov''è qualcosa che {name2} ha nascosto. E {name2} lo sa che {name1} sa. Ed è per questo che si trattano con quella gentilezza esagerata.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il confessore di {name1} ha dovuto interrompere la confessione a metà perché "le normali categorie del peccato non erano sufficienti". Ha poi dovuto consultarsi con il vescovo. Il vescovo ha detto solo: "e {name2}?".'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Una vecchia cartolina ritrovata, indirizzo: {name1}. Testo: "non dimenticherò mai quella settimana. Specialmente martedì. Specialmente ciò che hai portato nella borsa il martedì." Mittente: {name2}.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il meccanico che ha riparato la macchina di {name1} descrive: "c''era sabbia. Molta sabbia. In posti dove la sabbia non dovrebbe mai arrivare. E un paio di cose lasciate nel portabagagli che non ho toccato e non toccherò mai."'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Stando alle voci che circolano: {name1} e {name2} si sono detti cose, quella sera, che non avevano mai detto a nessun altro. E non le riprenderanno indietro. E questo li/le lega in un modo che nessun contratto potrebbe formalizzare.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Il testimone della terza età ricorda: "li ho visti uscire dalla legnaia, {name1} e {name2}. Avevano entrambi foglie nei capelli e un''aria soddisfatta che dà da pensare. Ho 78 anni. Ho capito tutto subito."'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Secondo fonti da ambienti notarili, {name1} e {name2} compaiono insieme in almeno tre documenti legali che non dovrebbero avere nessun motivo di avere in comune. I documenti esistono. Nessuno li ha richiesti.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'La nota nella Pro Loco locale: il premio "Coppia più incomprensibile dell''anno" va a {name1} e {name2}, per ragioni che il comitato giudicatore non ha voluto mettere per iscritto. La targa è stata comunque consegnata.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Stando a quanto riportato dal gestore del campeggio: "{name1} e {name2} hanno prenotato una tenda singola per due. La notte è stata silenziosa ma i vicini di tenda si sono spostati spontaneamente alle 2. Non hanno spiegato il motivo."'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'Nel testamento di un''anziana zia di {name1} è scritto: "lascio i miei risparmi a {name1}, a patto che smetta quella cosa con {name2} che tutti sanno ma nessuno nomina." {name1} ha ereditato comunque. Non ha smesso.'),
  ((SELECT id FROM categories WHERE slug = 'segreto'), 'L''investigatore privato ingaggiato da una parte non identificata riferisce: "{name1} e {name2} si muovono con una coordinazione che suggerisce anni di pratica comune. Il dossier è completo. Non lo pubblicherò per ragioni personali."');
