-- Migration 0011: anti-roma, anti-lazio, anti-milan, palestra, consiglio, motivazione, giudizio
-- 7 nuove categorie, ~280 contenuti

-- ============================================================
-- NUOVE CATEGORIE
-- ============================================================

INSERT INTO categories (slug, name, type, description) VALUES
  ('anti-roma', 'Anti-Roma', 'text', 'Sfotto'' per tifosi romanisti'),
  ('anti-lazio', 'Anti-Lazio', 'text', 'Sfotto'' per tifosi laziali'),
  ('anti-milan', 'Anti-Milan', 'text', 'Sfotto'' per tifosi milanisti'),
  ('palestra', 'Palestra', 'text', 'Risposte sarcastiche per finti sportivi e palestrati'),
  ('consiglio', 'Consiglio', 'text', 'Consigli di vita assolutamente pessimi'),
  ('motivazione', 'Motivazione', 'text', 'Frasi motivazionali che iniziano bene e finiscono male'),
  ('giudizio', 'Giudizio', 'text', 'Giudizi brutali su qualsiasi cosa');

-- ─── ANTI-ROMA ──────────────────────────────────────────────────────────────
INSERT INTO text_responses (category_id, content) VALUES
((SELECT id FROM categories WHERE slug = 'anti-roma'), 'Ue'' {name}, ma ancora tifi Roma? L''ultima volta che hanno vinto qualcosa c''erano ancora le lire.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), '{name}, la Roma e'' come il WiFi del treno: ti da'' speranza ma non funziona mai.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), 'La Roma? Ah si'', quella squadra che vince lo scudetto solo su Football Manager.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), '{name}, tifare Roma e'' come giocare alla lotteria: sai gia'' che perdi, ma ci speri lo stesso.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), 'La Roma ha piu'' allenatori esonerati che trofei in bacheca. Complimenti {name}!'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), '{name}, la Roma e'' l''unica squadra che riesce a farti piangere piu'' di una cipolla.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), 'Daje Roma daje! Ma daje dove? In Serie B?'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), '{name}, i romanisti sono come i vegani: non li cerchi, ma te lo vengono sempre a dire.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), 'La Roma e'' come un''ex: ti fa soffrire, ma non riesci a mollarla. Vero {name}?'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), '{name}, l''ultima Conference League l''avete festeggiata come un Mondiale. Dice tutto.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), 'La Roma gioca cosi'' male che pure i piccioni dell''Olimpico se ne vanno al primo tempo.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), '{name}, la Roma e'' come il Colosseo: un rudere glorioso che vive di ricordi.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), 'Senti {name}, la Roma quest''anno lotta per lo scudetto! ...quello della Primavera.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), 'La Roma e'' la dimostrazione che la sofferenza e'' una scelta. E {name} l''ha fatta.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), '{name}, "Romanista convinto" e'' un ossimoro.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), 'La Roma e'' come il caffe'' del distributore: fa schifo, ma i romanisti come {name} se lo bevono lo stesso.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), '{name}, la Roma ha cosi'' pochi trofei che la bacheca la usano come guardaroba.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), 'Tifare Roma e'' un po'' come credere a Babbo Natale: bello da piccoli, da grandi e'' imbarazzante. Vero {name}?'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), '{name}, la Roma gioca talmente male che i telecronisti mettono la modalita'' aereo.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), 'La Roma e'' l''unica squadra dove l''abbonamento costa piu'' dei trofei che vince.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), '{name}, la difesa della Roma ha piu'' buchi del Colosseo.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), 'La Roma quest''anno puo'' vincere tutto! Il torneo parrocchiale di Testaccio.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), '{name}, ma lo sai che "Roma" al contrario fa "amor"? Peccato che nessuno la ami.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), 'La Roma e'' come un trauma: la vivi, la subisci, e poi ti serve la terapia. Coraggio {name}!'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), '{name}, la Roma fa cosi'' pena che pure il lupo nel simbolo si sta cercando un''altra squadra.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), 'Io rispetto i romanisti come {name}. Ci vuole coraggio a presentarsi in pubblico con quella maglia.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), '{name}, la Roma e'' come la carbonara fatta male: tutti dicono che e'' buona per educazione.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), 'La Roma e'' l''unica squadra che fa rimpiangere la monarchia. Almeno il Re vinceva le guerre.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), '{name}, i romanisti hanno un solo superpotere: la capacita'' di soffrire in silenzio. Anzi no, manco in silenzio.'),
((SELECT id FROM categories WHERE slug = 'anti-roma'), 'La Roma e'' come il Grande Raccordo Anulare: giri giri e non arrivi mai da nessuna parte.'),

-- ─── ANTI-LAZIO ─────────────────────────────────────────────────────────────
((SELECT id FROM categories WHERE slug = 'anti-lazio'), 'Ue'' {name}, tifi Lazio? Certo, qualcuno deve pur tifare le comparse.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), '{name}, la Lazio e'' come il fratello sfigato della Roma: esiste, ma nessuno se ne accorge.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), 'La Lazio e'' l''unica squadra dove il presidente e'' piu'' famoso dei giocatori. Bravo Lotito!'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), '{name}, la Lazio ha vinto uno scudetto nel 2000 e da allora campano di rendita. Come Lotito.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), 'La Lazio e'' come l''acqua frizzante: qualcuno la preferisce, ma e'' fondamentalmente sbagliata.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), '{name}, tifare Lazio e'' come comprare un''auto usata da Lotito: sai che ti frega, ma ci caschi.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), 'La Lazio gioca cosi'' male che pure le aquile dello stemma vorrebbero migrare altrove.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), '{name}, la Lazio e'' come il secondo piatto che nessuno ha ordinato: arriva e non lo vuole nessuno.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), 'Forza Lazio! ...scusa, mi e'' scappato da ridere.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), '{name}, l''Olimpico quando gioca la Lazio e'' cosi'' vuoto che ci senti l''eco.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), 'La Lazio e'' la dimostrazione che i soldi non fanno la felicita''. Soprattutto quelli di Lotito.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), '{name}, la Lazio ha piu'' comunicati stampa di Lotito che gol in campionato.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), 'La Lazio e'' come il cugino che nessuno invita a Natale ma si presenta lo stesso.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), '{name}, la Lazio e'' l''unica squadra che fa sembrare la Roma una grande.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), 'Tifare Lazio e'' come mettere la maionese sulla pasta: puoi farlo, ma perche''?'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), '{name}, la Lazio e'' come un semaforo rosso: la vedi, sai che c''e'', ma non la consideri.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), 'La Lazio con Lotito presidente e'' come una barzelletta che non fa ridere: lunga e triste.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), '{name}, la Lazio e'' cosi'' scarsa che pure i laziali tifano contro.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), 'La Lazio e'' come il lunedi'': nessuno la vuole, ma arriva lo stesso.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), '{name}, l''aquila della Lazio vola basso. Bassissimo. Tipo sotto terra.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), 'La Lazio ha cosi'' poca storia che Wikipedia la confonde con la regione.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), '{name}, tifare Lazio richiede una capacita'' di sofferenza che manco i monaci tibetani.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), 'La Lazio e'' come un compleanno senza torta: deludente e inutile.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), '{name}, la Lazio e'' talmente scarsa che gioca contro se stessa e perde.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), 'La Lazio e'' l''unica squadra dove il pullman arriva prima dei tifosi. Perche'' non ne ha.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), '{name}, se la sofferenza bruciasse calorie, i laziali sarebbero tutti modelli.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), 'La Lazio e'' come la password del WiFi: complicata, inutile e nessuno la ricorda.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), '{name}, la Lazio e'' il motivo per cui esiste il telecomando: per cambiare canale.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), 'Senti {name}, non ce l''ho con te. Ce l''ho con chi ti ha fatto diventare laziale.'),
((SELECT id FROM categories WHERE slug = 'anti-lazio'), 'La Lazio e'' come il pandoro a Natale: c''e'', ma tutti preferiscono il panettone.'),

-- ─── ANTI-MILAN ─────────────────────────────────────────────────────────────
((SELECT id FROM categories WHERE slug = 'anti-milan'), 'Ue'' {name}, tifi Milan? L''ultima Champions l''hai festeggiata che ancora avevi i capelli.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), '{name}, il Milan e'' come un nonno: vive di ricordi e racconta sempre le stesse storie.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), 'Il Milan di oggi e'' come un film di Natale su Canale 5: lo guardi per noia, non per piacere.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), '{name}, il Milan ha piu'' cambi di proprietario che trofei negli ultimi 10 anni.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), 'Il Milan e'' come un ristorante stellato che adesso fa kebab: gloriosa decadenza.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), '{name}, il Diavolo rossonero? Ormai e'' un diavoletto. Col pitchfork di plastica.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), 'Il Milan e'' come un ex ricco che adesso fa il barista: bei tempi quelli, eh {name}?'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), '{name}, San Siro piange ogni volta che vede il Milan giocare. E pure io.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), 'Il Milan e'' l''unica squadra che ha piu'' amministratori delegati che vittorie stagionali.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), '{name}, tifare Milan nel 2026 e'' come collezionare fax: un hobby triste e anacronistico.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), 'Forza Milan! ...di volonta'' per guardarli giocare.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), '{name}, il Milan gioca come mia nonna guida: lento, pericoloso e con tante bestemmie.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), 'Il Milan e'' come il pandoro: tutti dicono che lo amano, ma in realta'' lo prendono solo quando non c''e'' di meglio.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), '{name}, il Milan ha talmente tanti debiti che manco il Monopoli li accetterebbe.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), 'Il Milan e'' come una canzone di Albano: famosa, ma solo per i vecchi.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), '{name}, il Milan e'' la dimostrazione che i soldi degli arabi non comprano la dignita''.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), 'Il Milan e'' come un treno di Trenitalia: in ritardo, deludente e pieno di scuse.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), '{name}, il Milan gioca talmente piano che lo sponsor dovrebbe essere una lumaca.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), 'I milanisti come {name} dicono "noi abbiamo la storia". Si'', e il Museo Egizio ha le mummie. Stessa energia.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), '{name}, il Milan e'' come la nebbia di Milano: c''e'', ma non si vede.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), 'Il Milan e'' l''unica squadra che fa rimpiangere Berlusconi. E ce ne vuole.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), '{name}, il Milan cambia allenatore piu'' spesso di quanto io cambi le lenzuola.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), 'Il Milan e'' come il Cenacolo di Leonardo: bellissimo, ma sta cadendo a pezzi.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), '{name}, il Milan e'' come la settimana della moda: tanta scena, poca sostanza.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), 'Il Milan e'' come un''app che non si aggiorna dal 2007: obsoleta e piena di bug.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), '{name}, casciavit e'' poco. Il Milan e'' proprio il cacciavite arrugginito che non gira piu''.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), 'Il Milan gioca come cucino io: male, ma con tanta presunzione. Giusto {name}?'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), '{name}, il Milan e'' come il monopattino: sembrava il futuro, ma e'' solo un fastidio.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), 'Il Milan e'' come il meta nel 2026: nessuno lo usa piu'', ma insiste a esistere.'),
((SELECT id FROM categories WHERE slug = 'anti-milan'), '{name}, il Milan e'' quella squadra che ti fa dire "almeno non tifo Lazio". E basta.'),

-- ─── PALESTRA / DIETA / FIT ────────────────────────────────────────────────
((SELECT id FROM categories WHERE slug = 'palestra'), 'Palestra? Ma se l''unico peso che alzi e'' la forchetta!'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Ah si'', la palestra! Quella cosa dove vai a gennaio e molli a febbraio.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Dieta? L''unica dieta che conosci e'' "DIEta pure tu che me fai veni'' i nervi".'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Bravo, vai in palestra! Cosi'' puoi fare selfie allo specchio e mettere la story.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'La palestra: dove paghi 50 euro al mese per sentirti in colpa quando non ci vai.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Fitness? Fit-in-this-pizza-in-my-mouth piuttosto.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Ah fai palestra? E allora perche'' sudi salendo le scale?'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Proteine? L''unica proteina che assumi e'' il ragout della nonna la domenica.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Squat? L''unico squat che fai e'' sederti sul cesso dopo il pranzo della domenica.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Crossfit? L''unico cross che fai e'' il cross tra divano e frigorifero.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Personal trainer? L''unico che ti allena e'' il corriere quando suona e devi correre ad aprire.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Addominali? Li hai, sono solo protetti da uno strato di protezione termica. Si chiama grasso.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Vai in palestra per la salute o per fare le stories su Instagram? Dai, lo sappiamo entrambi.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'La tua dieta dura meno di una storia su Instagram: 24 ore e scompare.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Fai cardio? L''unico cardio che fai e'' correre dietro al cameriere per ordinare il dolce.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Workout? Il tuo workout e'' alzarti dal divano per prendere il telecomando.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Creatina, BCAA, proteine in polvere... fratello, hai provato a fare semplicemente le scale?'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'La palestra e'' come il dentista: sai che ci dovresti andare, ma trovi sempre una scusa.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Ah sei a dieta? Bello. E quella pizza che hai mangiato ieri sera era di verdure immagino.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Leg day? L''unico leg day che conosci e'' quando corri per prendere l''autobus.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Hai detto palestra? Il tuo corpo e'' un tempio. Si'', un tempio azteco: in rovina.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Vai in palestra per dimagrire e poi ti fai la birra post-allenamento. Stonks.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'La tua forma fisica? Un cerchio. Il cerchio e'' una forma.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Sei a dieta? Bene! Ricorda: la Nutella non e'' un gruppo alimentare.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Allenamento? L''unico allenamento che fai e'' lo slalom tra le scuse.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Fai pesi? Si'', pesi 120 kg.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'La palestra: l''unico posto dove sudi per sembrare uguale a prima.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Bodybuilding? L''unica cosa che stai building e'' il debito con il nutrizionista.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Hai la tartaruga! Si'', quella che cammina piano piano e si nasconde nel guscio.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Sei fit? Fit de che? Fit-tuso forse.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'La dieta inizia sempre "da lunedi''". Quale lunedi''? Quello di mai.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Bilanciere? L''unico bilanciere che usi e'' quello tra pizza e kebab la sera.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Fai yoga? L''unica posizione che padroneggi e'' quella fetale davanti a Netflix.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Integrazione sportiva? Fratello, integra prima un po'' di dignita''.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Dici "sono in massa" da 3 anni. Bro, quella non e'' massa, e'' lardo.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Il tuo metabolismo e'' cosi'' lento che pure le tartarughe ti sorpassano.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Hai l''abbonamento in palestra? Bravo. Ce l''hai anche il coraggio di usarlo?'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Muscoli? Il tuo muscolo piu'' sviluppato e'' il pollice dallo scrollare Instagram.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'Dici che mangi sano ma il tuo Glovo parla chiaro: 3 McDonald''s questa settimana.'),
((SELECT id FROM categories WHERE slug = 'palestra'), 'La prossima volta che dici "palestra" ti mando una foto del tuo frigorifero come reality check.'),

-- ─── CONSIGLIO ──────────────────────────────────────────────────────────────
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio del giorno: se la vita ti da'' limoni, spruzzali negli occhi dei tuoi nemici.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Vuoi un consiglio? Fatti i cazzi tuoi. Ecco, questo e'' il miglior consiglio che riceverai mai.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio: se qualcuno ti dice "sii te stesso", probabilmente non ti conosce bene.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio della nonna: non fidarti mai di chi mette il ketchup sulla pasta.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Ecco un consiglio gratis: i soldi non fanno la felicita''. Ma e'' meglio piangere in Ferrari che in autobus.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio: prima di parlare, pensa. E dopo aver pensato, stai zitto.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Il mio consiglio? Smetti di chiedere consigli a un bot. Questo la dice lunga su di te.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio: se il tuo capo ti dice "sei come un figlio per me", aggiorna il CV.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Vuoi un consiglio? Non seguire mai i consigli di chi vive peggio di te.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio: se la tua ex ti scrive "mi manchi", cambia numero, citta'' e identita''.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio finanziario: risparmia. Come? Smettila di comprare cazzate su Amazon alle 3 di notte.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio: non dire mai "potrebbe andare peggio". L''universo lo prende come una sfida.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio di vita: mangia bene, dormi bene, fai sport. O in alternativa, fregatene di tutto.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio: se qualcuno ti dice "dobbiamo parlare", scappa. Non e'' mai una cosa bella.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Ecco il mio consiglio: non prendere la vita troppo sul serio. Tanto non ne esci vivo.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio: se non sai cosa fare della tua vita, almeno non fare danni.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio del giorno: se il lunedi'' fa schifo, ricordati che il martedi'' fa schifo uguale.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio: la vendetta e'' un piatto che va servito freddo. Come la pizza del giorno prima.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Vuoi un consiglio? Smetti di lamentarti. Ah no, aspetta, quello e'' l''unico sport che fai.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio: se ti senti inutile, ricordati che qualcuno ha progettato il clacson delle Smart.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio pratico: non discutere con gli idioti. Ti trascinano al loro livello e ti battono con l''esperienza.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio: quando la vita chiude una porta, controlla se c''e'' una finestra. Per buttarti? No, per l''aria condizionata.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio: non mettere mai in discussione la tua intelligenza. Tanto lo fanno gia'' gli altri.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Ecco un consiglio: tratta gli altri come vorresti essere trattato. Cioe'' male, a quanto pare.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio: impara dai tuoi errori. Con la quantita'' che fai, diventerai un genio.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio: se ti dicono "esprimi un desiderio", non sprecare il desiderio chiedendo un altro desiderio. Chiedi i soldi.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio relazionale: se lui/lei non ti risponde, non e'' impegnato/a. Ti sta ignorando.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio: non cercare la perfezione. Con la tua faccia sarebbe un obiettivo irraggiungibile.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio: segui i tuoi sogni! Ma prima metti la sveglia, che domani lavori.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio: se tutti ti dicono che hai torto, hai due opzioni. O cambi idea, o cambi amici.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio: quando senti "l''importante e'' partecipare", significa che hai gia'' perso.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio: non avere rimpianti. A meno che non hai rifiutato Bitcoin a 1 euro. Allora piangi.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio professionale: rispondi sempre "ci penso" alle email. Poi non pensarci.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio: la pazienza e'' la virtu'' dei forti. Tu pero'' non sei forte, quindi incazzati pure.'),
((SELECT id FROM categories WHERE slug = 'consiglio'), 'Consiglio: fai quello che ami e non lavorerai neanche un giorno. Perche'' nessuno ti assume per guardare Netflix.'),

-- ─── MOTIVAZIONE ────────────────────────────────────────────────────────────
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Credi in te stesso! Tanto sei l''unico che lo fa.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Non mollare mai! A meno che non sia una dieta, un lavoro, una relazione, o qualsiasi cosa.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Ogni giorno e'' un nuovo inizio! Per fare gli stessi identici errori di ieri.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Sei unico! Come tutti gli altri 8 miliardi di persone su questo pianeta.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Il successo e'' dietro l''angolo! Peccato che tu stia girando in tondo.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Segui il tuo cuore! Ma anche il navigatore, che il cuore non sa leggere le mappe.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Puoi fare tutto cio'' che vuoi! Tranne le cose che richiedono talento, soldi o impegno.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Se cadi sette volte, rialzati otto! Oppure resta a terra, che il pavimento e'' comodo.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Sei una stella! Di quelle che sono morte milioni di anni fa ma la luce arriva ancora.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Non arrenderti! Hai ancora tantissimi modi per fallire che non hai provato.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'La vita e'' bella! Disse nessuno il lunedi'' mattina alle 6.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Sii il cambiamento che vuoi vedere nel mondo! Basta che non cambi canale durante la partita.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Ce la puoi fare! Ma probabilmente no. Pero'' provaci, cosi'' almeno ridiamo.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Ogni fallimento e'' un passo verso il successo! Tu pero'' stai facendo la maratona.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Sei forte come una roccia! Peccato che la roccia non si muove e non fa un cazzo.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Il futuro appartiene a chi crede nei propri sogni! E a chi ha i genitori ricchi. Soprattutto a quelli.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Non e'' mai troppo tardi per ricominciare! Tranne alle 17:01 alla posta, li'' e'' tardi eccome.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Hai un potenziale infinito! Infinitamente basso, ma sempre infinito.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Il mondo e'' pieno di opportunita''! Ma tu sei pieno di scuse, quindi pari e patta.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Sii positivo! Come il tuo conto in banca non e''.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Oggi e'' il primo giorno del resto della tua vita! Che sara'' probabilmente uguale a ieri.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Punta alle stelle! Cosi'' quando atterri nella merda, almeno sai che hai provato.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Niente e'' impossibile! Tranne leccarti il gomito. Provaci e capirai i tuoi limiti.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Sei un guerriero! Di quelli che muoiono nei primi 5 minuti del film.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'La perseveranza paga sempre! A meno che non stai perseverando nella direzione sbagliata. Come ora.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Circondati di persone positive! Ah, non ne conosci? Vabbeh, ci sono io. Che non sono positivo.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Sii la versione migliore di te stesso! Che la versione attuale fa abbastanza pena.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'La fortuna aiuta gli audaci! E gli altri? Si attaccano al cazzo.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Il segreto del successo e'' la costanza! Sei costante. Costantemente nella merda, ma costante.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Domani sara'' un giorno migliore! Dicevi anche ieri e guarda dove siamo.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Credi nei miracoli! Del resto, il fatto che tu sia arrivato fin qui ne e'' gia'' uno.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'L''importante non e'' vincere, ma partecipare! Lo dicono solo quelli che perdono.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Chi la dura la vince! Tu pero'' duri poco in tutto. Chiedi alla tua ex.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'Sei un diamante grezzo! Molto grezzo. Troppo grezzo. Forse sei un sasso.'),
((SELECT id FROM categories WHERE slug = 'motivazione'), 'I limiti esistono solo nella tua mente! E nel tuo conto corrente, e nella tua forma fisica, e...'),

-- ─── GIUDIZIO ───────────────────────────────────────────────────────────────
((SELECT id FROM categories WHERE slug = 'giudizio'), 'Il mio giudizio su {name}? Una merda. Prossima domanda.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), '{name}? Su una scala da 1 a 10, un bel "ma anche no".'),
((SELECT id FROM categories WHERE slug = 'giudizio'), 'Giudizio su {name}: come una supposta. Nessuno lo vuole, ma qualcuno deve prenderlo.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), '{name}? Sarebbe un insulto agli insulti dare un giudizio. Pero'' lo faccio: fa cagare.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), 'Il mio verdetto su {name}: manco se me lo regalano. Anzi, manco se mi pagano.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), '{name}? Ho visto cose migliori nel cestino dell''umido.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), 'Giudizio finale su {name}: Dio ha creato il mondo in 7 giorni. {name} lo distrugge in 5 minuti.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), '{name}: 2 stelle su 5. Una perche'' esiste, l''altra per pieta''.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), 'Il mio giudizio su {name}? Come un incidente stradale: orribile, ma non riesci a non guardare.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), '{name}? L''equivalente umano di un calzino bagnato. Scomodo e inutile.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), 'Giudizio su {name}: peggio della coda in tangenziale il venerdi'' sera. E quella gia'' fa schifo.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), '{name}? Se fosse un film, sarebbe straight-to-DVD. Anzi, straight-to-cestino.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), '{name}: lo promuovo! A disastro nazionale.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), 'Il mio giudizio su {name}: e'' come l''appendice. Esiste, ma nessuno sa perche''.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), '{name}? Immagina il peggior giudizio possibile. Ecco, peggio.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), 'Giudizio su {name}: se la delusione avesse un volto, sarebbe {name}.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), '{name}: unica nota positiva e'' che prima o poi finisce.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), '{name}? Giudizio: come la maionese scaduta. Nessuno la vuole, ma sta sempre li'' in frigo.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), 'Il mio verdetto su {name}: poteva andare peggio. No aspetta, non poteva.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), '{name}: una stella. Solo perche'' zero non si puo''.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), 'Giudizio su {name}: come la pubblicita'' prima del video di YouTube. Fastidioso e troppo lungo.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), '{name}? Se la mediocritas fosse un traguardo, saresti un campione olimpico.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), '{name}: talmente brutto/a che pure il giudizio si rifiuta di uscire.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), 'Il mio giudizio su {name}: come il lunedi''. Nessuno lo vuole, nessuno lo ha chiesto, eppure eccolo qua.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), '{name}? Bocciato. Bocciato forte. Bocciato con rincorsa.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), 'Giudizio su {name}: se fosse un piatto, sarebbe la pasta scotta con il ketchup.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), '{name}: giudizio positivo! ...per chi lo evita.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), '{name}? Come un regalo di Natale dalla zia: non lo vuoi, ma devi far finta di apprezzare.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), 'Il mio giudizio autorevole su {name}: meh. Anzi, bleah.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), '{name}: l''unica cosa giudicabile e'' il coraggio di chi lo ha proposto.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), 'Giudizio su {name}: se fosse un suono, sarebbe il rumore del polistirolo. Insopportabile.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), '{name}: voto 4. Ma solo perche'' oggi sono generoso.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), '{name}? Il mio giudizio e'' come il tuo futuro: nero.'),
((SELECT id FROM categories WHERE slug = 'giudizio'), 'Giudizio su {name}: Wikipedia lo classificherebbe sotto "errori della natura".'),
((SELECT id FROM categories WHERE slug = 'giudizio'), '{name}? Promosso! A peggior cosa che abbia mai giudicato.');
